"""Extended immutable workflow specifications."""

from __future__ import annotations

from typing import Callable

from src.agent.task_workflows import (
    CollectionBehavior,
    ConfirmationPolicy,
    EffectClass,
    ParameterRequirement,
    StandardTaskKind,
    TaskResource,
    WorkflowSpec,
)
from src.agent.workflow_compilers_extended import (
    compile_article as _compile_article,
    compile_batch_analysis as _compile_batch_analysis,
    compile_batch_management as _compile_batch_management,
    compile_collection_filter as _compile_collection_filter,
    compile_data_health as _compile_data_health,
    compile_export as _compile_export,
    compile_feed_read as _compile_feed_read,
    compile_formal_analysis as _compile_formal_analysis,
    compile_group as _compile_group,
    compile_history as _compile_history,
    compile_notification as _compile_notification,
    compile_schedule as _compile_schedule,
    compile_screening as _compile_screening,
    compile_source_discovery as _compile_source_discovery,
    compile_template as _compile_template,
    compile_theme_discovery as _compile_theme_discovery,
    compile_theme_evidence as _compile_theme_evidence,
    compile_transform as _compile_transform,
    compile_watchlist_mutation as _compile_watchlist_mutation,
    compile_watchlist_query as _compile_watchlist_query,
    compile_web as _compile_web,
)
from src.agent.workflow_compilers_primary import compile_no_tools as _compile_no_tools


def build_extended_registry(
    spec_factory: Callable[..., WorkflowSpec],
    requirement_factory: Callable[..., ParameterRequirement],
) -> dict[StandardTaskKind, WorkflowSpec]:
    return {
            StandardTaskKind.THEME_STOCK_DISCOVERY: spec_factory(
                StandardTaskKind.THEME_STOCK_DISCOVERY,
                "领域找股",
                "按语义产业领域从内部结构化板块和完整股票池找候选。",
                {"get_domain_stock_candidates"},
                _compile_theme_discovery,
                resources={"concept_board_catalog"},
                input_resource_parameters={"domains": TaskResource.DOMAIN_COLLECTION},
                parameter_output_resources={"domains": TaskResource.DOMAIN_COLLECTION},
                collection=CollectionBehavior.SOURCE,
                result_contract="theme_stock_discovery",
                max_output_entities=6000,
            ),
            StandardTaskKind.THEME_BUSINESS_EVIDENCE: spec_factory(
                StandardTaskKind.THEME_BUSINESS_EVIDENCE,
                "逐股主题业务分析",
                "对结构化候选集合中的每一只股票分别建立公司资料、主营、公告、个股新闻和个股研报证据档案，再逐股判断主题匹配和发展强度；不得用行业新闻命中代替逐股分析。",
                {
                    "get_company_theme_evidence",
                    "search_financial_news",
                    "search_research_library",
                },
                _compile_theme_evidence,
                requirements=(
                    requirement_factory(
                        when={"candidate_scope": {"candidate_collection"}},
                        entities=True,
                    ),
                ),
                input_resources={TaskResource.SECURITY_COLLECTION},
                input_resource_parameters={"domains": TaskResource.DOMAIN_COLLECTION},
                collection=CollectionBehavior.SOURCE,
                result_processor="company_evidence_binding",
                result_contract="theme_business_evidence",
                max_tool_calls=6000,
                max_parallel_steps=4,
                allow_partial_tool_failures=True,
                max_input_entities=6000,
                max_output_entities=6000,
            ),
            StandardTaskKind.STOCK_SCREENING: spec_factory(
                StandardTaskKind.STOCK_SCREENING,
                "股票筛选",
                "按完整强类型筛选规格执行全市场量化筛选。",
                {"screen_atr_volatility_stocks"},
                _compile_screening,
                collection=CollectionBehavior.SOURCE,
                result_contract="stock_screening",
            ),
            StandardTaskKind.COLLECTION_FINANCIAL_FILTER: spec_factory(
                StandardTaskKind.COLLECTION_FINANCIAL_FILTER,
                "集合财务筛选",
                "用一组强类型财务条件筛选完整公司集合；所有条件共同决定最终保留集合。",
                {"get_multi_stock_financials"},
                _compile_collection_filter,
                entities=True,
                max_tool_calls=104,
                max_parallel_steps=4,
                collection=CollectionBehavior.FILTER,
                result_contract="collection_financial_filter",
            ),
            StandardTaskKind.WATCHLIST_QUERY: spec_factory(
                StandardTaskKind.WATCHLIST_QUERY,
                "自选查询",
                "查看自选或在指定自选集合内按语义领域筛选。",
                {"manage_watchlist", "filter_watchlist_by_theme"},
                _compile_watchlist_query,
                resources={"concept_board_catalog"},
            ),
            StandardTaskKind.WATCHLIST_MUTATION: spec_factory(
                StandardTaskKind.WATCHLIST_MUTATION,
                "自选修改",
                "按用户明确要求添加或移除自选股。",
                {"manage_watchlist"},
                _compile_watchlist_mutation,
                entities=True,
                effect=EffectClass.MUTATION,
                confirmation_actions={"add", "remove"},
            ),
            StandardTaskKind.WATCHLIST_GROUP_MANAGEMENT: spec_factory(
                StandardTaskKind.WATCHLIST_GROUP_MANAGEMENT,
                "自选分组管理",
                "查看、创建、重命名、删除或修改自选分组成员。",
                {"manage_watchlist_groups"},
                _compile_group,
                effect=EffectClass.MUTATION,
                confirmation_actions={"create", "rename", "delete", "add", "remove"},
                requirements=(requirement_factory(when={"action": {"add", "remove"}}, entities=True),),
            ),
            StandardTaskKind.DATA_HEALTH: spec_factory(
                StandardTaskKind.DATA_HEALTH,
                "数据健康",
                "查看股票池、行情和财务数据覆盖与维护状态。",
                {"get_data_health"},
                _compile_data_health,
            ),
            StandardTaskKind.FORMAL_ANALYSIS: spec_factory(
                StandardTaskKind.FORMAL_ANALYSIS,
                "正式分析",
                "启动持久化单股报告，或查询其运行状态。",
                {"run_stock_analysis", "get_analysis_status"},
                _compile_formal_analysis,
                effect=EffectClass.MUTATION,
                confirmation_actions={"start"},
                requirements=(requirement_factory(when={"action": {"start"}}, entities=True),),
            ),
            StandardTaskKind.ANALYSIS_HISTORY: spec_factory(
                StandardTaskKind.ANALYSIS_HISTORY,
                "分析历史",
                "搜索、读取或删除已保存的正式分析报告。",
                {"search_analysis_history", "read_analysis_report", "delete_analysis_history"},
                _compile_history,
                effect=EffectClass.MUTATION,
                confirmation_actions={"delete"},
            ),
            StandardTaskKind.ANALYSIS_TEMPLATE_MANAGEMENT: spec_factory(
                StandardTaskKind.ANALYSIS_TEMPLATE_MANAGEMENT,
                "分析模板",
                "查看或管理正式分析模板。",
                {"manage_analysis_templates"},
                _compile_template,
                effect=EffectClass.MUTATION,
                confirmation_actions={"create", "update", "set_default", "delete"},
            ),
            StandardTaskKind.BATCH_ANALYSIS: spec_factory(
                StandardTaskKind.BATCH_ANALYSIS,
                "批量分析",
                "按明确范围启动正式批量分析。",
                {"run_batch_analysis"},
                _compile_batch_analysis,
                effect=EffectClass.MUTATION,
                confirmation_policy=ConfirmationPolicy.ALWAYS,
                requirements=(
                    requirement_factory(when={"scope": {"symbols"}}, entities=True),
                    requirement_factory(when={"scope": {"group"}}, confirmation=True),
                    requirement_factory(when={"scope": {"watchlist", "configured"}}, confirmation=True),
                ),
            ),
            StandardTaskKind.BATCH_RUN_MANAGEMENT: spec_factory(
                StandardTaskKind.BATCH_RUN_MANAGEMENT,
                "批量任务管理",
                "查看或控制批量分析任务。",
                {"manage_batch_run"},
                _compile_batch_management,
                effect=EffectClass.MUTATION,
                confirmation_actions={"pause", "continue", "resume_failed", "regenerate_report", "notify", "stop", "delete"},
            ),
            StandardTaskKind.ANALYSIS_SCHEDULE_MANAGEMENT: spec_factory(
                StandardTaskKind.ANALYSIS_SCHEDULE_MANAGEMENT,
                "定时分析",
                "查看或修改自动分析计划。",
                {"manage_analysis_schedule"},
                _compile_schedule,
                effect=EffectClass.MUTATION,
                confirmation_actions={"update"},
            ),
            StandardTaskKind.NOTIFICATION: spec_factory(
                StandardTaskKind.NOTIFICATION,
                "通知",
                "检查通知配置或发送用户明确指定的内容。",
                {"get_notification_status", "send_notification"},
                _compile_notification,
                effect=EffectClass.EXTERNAL,
                confirmation_policy=ConfirmationPolicy.CONDITIONAL,
                confirmation_actions={"send"},
            ),
            StandardTaskKind.FINANCIAL_SOURCE_DISCOVERY: spec_factory(
                StandardTaskKind.FINANCIAL_SOURCE_DISCOVERY,
                "资讯源查询",
                "列出或检查指定财经资讯源。",
                {"list_financial_sources", "inspect_financial_source"},
                _compile_source_discovery,
            ),
            StandardTaskKind.FINANCIAL_FEED_READ: spec_factory(
                StandardTaskKind.FINANCIAL_FEED_READ,
                "Feed读取",
                "按已知路由读取一个财经 Feed。",
                {"read_financial_feed"},
                _compile_feed_read,
            ),
            StandardTaskKind.FINANCIAL_ARTICLE_READ: spec_factory(
                StandardTaskKind.FINANCIAL_ARTICLE_READ,
                "文章读取",
                "读取用户指定的一篇财经资讯正文。",
                {"read_financial_article"},
                _compile_article,
            ),
            StandardTaskKind.WEBPAGE_FEED_TRANSFORM: spec_factory(
                StandardTaskKind.WEBPAGE_FEED_TRANSFORM,
                "网页转Feed",
                "按用户提供的网页和选择器生成 Feed 预览。",
                {"transform_webpage_to_feed"},
                _compile_transform,
            ),
            StandardTaskKind.FINANCIAL_FEED_EXPORT: spec_factory(
                StandardTaskKind.FINANCIAL_FEED_EXPORT,
                "Feed导出",
                "导出用户明确指定的财经 Feed。",
                {"export_financial_feed"},
                _compile_export,
                effect=EffectClass.EXTERNAL,
                confirmation_policy=ConfirmationPolicy.ALWAYS,
            ),
            StandardTaskKind.PUBLIC_WEB_RESEARCH: spec_factory(
                StandardTaskKind.PUBLIC_WEB_RESEARCH,
                "公开网页研究",
                "当用户明确要求联网，或完成当前时效性研究目标确实缺少内部权威来源时，检索或读取公开网页；不得替代已有结构化金融能力。",
                {"websearch", "webfetch"},
                _compile_web,
            ),
            StandardTaskKind.TRADE_EXECUTION: spec_factory(
                StandardTaskKind.TRADE_EXECUTION,
                "交易执行",
                "交易类请求只能进入独立状态机；当前系统未接入账户、风控和下单工具。",
                (),
                _compile_no_tools,
                effect=EffectClass.TRADE,
                confirmation_policy=ConfirmationPolicy.ALWAYS,
                enabled=False,
                state_machine=("参数校验", "账户检查", "风控检查", "用户确认", "下单", "订单状态"),
            ),
        }


__all__ = ["build_extended_registry"]
