"""Tool-result compaction handlers, group 2."""

from __future__ import annotations

from api.v1.endpoints.agent.tools import (
    json,
    logging,
    datetime,
    Any,
    Dict,
    List,
    logger,
    LLM_ARRAY_LIMIT,
    LLM_SERIES_LIMIT,
    _format_result,
    _pick_fields,
    _trim_list,
    _annotate_tool_payload,
    _normalize_stock_info,
    _compact_time_series,
 )

__all__ = ['_compact_tool_group2']


def _compact_tool_group2(tool_name: str, result: dict[str, object]) -> object:
    if tool_name in {"get_financials", "get_balance_sheet", "get_income_statement", "get_cashflow"}:
        series_key = "items"
        if tool_name == "get_balance_sheet":
            series_key = "balance_sheet"
        elif tool_name == "get_income_statement":
            series_key = "income_statement"
        elif tool_name == "get_cashflow":
            series_key = "cashflow"
        series = result.get(series_key, [])
        return _annotate_tool_payload(
            tool_name,
            {
                "symbol": result.get("symbol"),
                "requested_periods": result.get("requested_periods"),
                "periods": len(series) if isinstance(series, list) else result.get("periods"),
                "latest": series[-1] if isinstance(series, list) and series else {},
                "recent_periods": series[-6:] if isinstance(series, list) else [],
                "amount_unit": result.get("amount_unit"),
                "ratio_unit": result.get("ratio_unit"),
                "per_share_unit": result.get("per_share_unit"),
                "currency": result.get("currency"),
                "basis": result.get("basis"),
                "flow_basis": result.get("flow_basis"),
                "balance_basis": result.get("balance_basis"),
                "source": result.get("source"),
                "sources": result.get("sources"),
                "source_url": result.get("source_url"),
                "success": result.get("success"),
                "partial": result.get("partial"),
                "errors": result.get("errors"),
                "data_time": result.get("data_time"),
                "is_stale": result.get("is_stale"),
                "fallback_used": result.get("fallback_used"),
                "_cached": result.get("_cached"),
                "_fetched_at": result.get("_fetched_at"),
            },
            payload_policy="compacted",
            compacted=True,
            compaction_reason="financial_recent_periods",
        )

    if tool_name == "get_valuation_ratios":
        return _annotate_tool_payload(
            tool_name,
            _pick_fields(
                result,
                [
                    "symbol",
                    "name",
                    "trade_date",
                    "history_trade_date",
                    "current_price",
                    "pe_static",
                    "pe_dynamic",
                    "pe_ttm",
                    "pb_mrq",
                    "pb_annual",
                    "ps_ttm",
                    "pcf_ttm",
                    "peg_trailing",
                    "peg_forward",
                    "peg_basis",
                    "forward_pe",
                    "forward_ps",
                    "forward_pe_current_year",
                    "forward_pe_next_year",
                    "dividend_yield_ttm_pct",
                    "cash_dividend_per_share_ttm",
                    "dividend_count_ttm",
                    "dividends_ttm",
                    "pe_percentiles",
                    "pe_history_stats",
                    "industry_rank",
                    "industry_benchmark",
                    "price_overdraft_signal",
                    "total_market_cap",
                    "circulating_market_cap",
                    "price_unit",
                    "market_cap_unit",
                    "ratio_unit",
                    "percent_unit",
                    "valuation_basis",
                    "sources",
                    "source_urls",
                    "success",
                    "partial",
                    "errors",
                    "data_time",
                    "data_time_inferred",
                    "is_stale",
                    "fallback_used",
                    "cache_detail",
                    "_cached",
                    "_fetched_at",
                ],
            ),
            payload_policy="compacted",
            compacted=True,
            compaction_reason="valuation_key_fields",
        )

    if tool_name == "get_shareholder_structure":
        return _annotate_tool_payload(
            tool_name,
            {
                **_pick_fields(
                    result,
                    [
                        "symbol",
                        "holder_count",
                        "top_holders_report_date",
                        "top_holder_item_count",
                        "institution_holding",
                        "institution_holding_ratio",
                        "institution_holding_ratio_basis",
                        "actual_controller",
                        "holder_change_item_count",
                        "units",
                        "source",
                        "sources",
                        "source_urls",
                        "source_scope",
                        "section_availability",
                        "success",
                        "partial",
                        "errors",
                        "warnings",
                        "data_time",
                        "holder_report_date",
                        "expected_latest_report_date",
                        "freshness_unknown",
                        "is_stale",
                        "fallback_used",
                        "cache_detail",
                        "_cached",
                        "_fetched_at",
                    ],
                ),
                "top_holders": _trim_list(
                    result.get("top_holders"),
                    10,
                    [
                        "rank",
                        "holder_name",
                        "holder_type",
                        "share_type",
                        "holding_shares",
                        "holding_ratio_pct",
                        "change_direction",
                        "change_shares",
                        "change_ratio_pct",
                    ],
                ),
                "holder_changes": _trim_list(
                    result.get("holder_changes"),
                    8,
                    [
                        "announcement_date",
                        "holder_name",
                        "change_direction",
                        "change_shares",
                        "signed_change_shares",
                        "average_price_yuan",
                        "remaining_shares",
                        "change_period",
                        "transaction_method",
                    ],
                ),
            },
            payload_policy="compacted",
            compacted=True,
            compaction_reason="shareholder_top_lists",
        )

    if tool_name in {
        "search_news",
        "get_announcements",
        "get_risk_events",
        "get_research_report",
        "get_social_sentiment",
    }:
        item_fields_map = {
            "search_news": [
                "title",
                "published",
                "source",
                "url",
                "source_type",
                "rss_route",
                "relevance",
                "relevance_score",
                "event_type",
                "event_label",
                "importance",
                "tags",
                "classification_method",
                "summary",
            ],
            "get_announcements": [
                "title",
                "publish_date",
                "notice_type",
                "source_notice_type",
                "url",
                "importance",
                "tags",
                "classification_method",
            ],
            "get_risk_events": [
                "title",
                "date",
                "source",
                "source_type",
                "url",
                "severity",
                "status",
                "risk_category",
                "risk_label",
                "risk_summary",
                "tags",
                "confidence",
                "evidence_basis",
                "requires_fulltext_verification",
                "classification_method",
            ],
            "get_research_report": [
                "title",
                "org",
                "rating",
                "publish_date",
                "industry",
                "url",
                "summary",
                "profit_forecasts",
                "monthly_report_count",
                "source",
                "source_type",
            ],
            "get_social_sentiment": [
                "title",
                "publish_time",
                "source",
                "author",
                "post_kind",
                "url",
                "label",
                "sentiment_score",
                "positive_hits",
                "negative_hits",
                "read_count",
                "reply_count",
                "classification_method",
                "page_number",
            ],
        }
        compact = _pick_fields(
            result,
            [
                "symbol",
                "name",
                "days",
                "limit",
                "type",
                "source",
                "sources",
                "sentiment_score",
                "overall_score",
                "positive_count",
                "negative_count",
                "neutral_count",
                "total_discussion",
                "user_post_count",
                "syndicated_info_count",
                "xueqiu_hot_count",
                "returned_item_order",
                "sentiment_sample_scope",
                "engagement_weighted_score",
                "sentiment_confidence",
                "total_read",
                "total_reply",
                "diagnose_score",
                "eastmoney_diagnose_score",
                "diagnose_score_semantics",
                "top_keywords",
                "analysis",
                "source_chain",
                "rss_routes",
                "item_count",
                "excluded_weak_mention_count",
                "success",
                "partial",
                "errors",
                "warnings",
                "data_time",
                "retrieved_at",
                "freshness_unknown",
                "is_stale",
                "has_announcements",
                "coverage_start",
                "coverage_end",
                "source_scope",
                "fallback_attempted",
                "has_risk_events",
                "has_reports",
                "max_pages",
                "coverage_complete",
                "fallback_used",
                "fallback_recommended",
                "fallback_query",
                "cache_detail",
                "_cached",
                "_fetched_at",
            ],
        )
        if "daily_trend" in result:
            compact["daily_trend"] = _trim_list(result.get("daily_trend"), LLM_ARRAY_LIMIT)
        if "score_trend" in result:
            compact["score_trend"] = _trim_list(result.get("score_trend"), LLM_ARRAY_LIMIT)
        compact["items"] = _trim_list(result.get("items"), LLM_ARRAY_LIMIT, item_fields_map[tool_name])
        compact["item_count"] = len(result.get("items") or [])
        return _annotate_tool_payload(
            tool_name,
            compact,
            payload_policy="compacted",
            compacted=True,
            compaction_reason="news_family_item_window",
        )

    if tool_name == "search_financial_news":
        compact = _pick_fields(
            result,
            [
                "query",
                "topic",
                "days",
                "success",
                "partial",
                "item_count",
                "rss_routes",
                "rss_catalog_count",
                "attempted_route_count",
                "successful_route_count",
                "web_fallback",
                "source",
                "errors",
                "warnings",
                "data_time",
                "retrieved_at",
                "is_stale",
                "freshness_unknown",
                "fallback_attempted",
                "fallback_used",
                "fallback_recommended",
            ],
        )
        compact["items"] = _trim_list(
            result.get("items"),
            6,
            [
                "id",
                "title",
                "summary",
                "content_text",
                "link",
                "published",
                "author",
                "tags",
                "image",
                "attachments",
                "source",
                "source_type",
                "rss_route",
                "rss_params",
                "content_fallback",
            ],
            {"summary": 800, "content_text": 1800},
        )
        return _annotate_tool_payload(
            tool_name,
            compact,
            payload_policy="compacted",
            compacted=True,
            compaction_reason="semantic_rss_item_and_text_window",
        )

    if tool_name in {"list_financial_sources", "discover_rss_sources"}:
        compact = _pick_fields(
            result,
            [
                "success",
                "partial",
                "catalog_count",
                "matched_count",
                "item_count",
                "returned_count",
                "has_more",
                "offset",
                "next_offset",
                "scope",
                "filters",
                "query_scope",
                "query_note",
                "applied_filters",
                "data_time",
                "is_stale",
                "freshness_unknown",
                "errors",
                "warnings",
            ],
        )
        compact["items"] = _trim_list(
            result.get("items"),
            50,
            [
                "route_path",
                "name",
                "namespace",
                "namespace_name",
                "description",
                "example",
                "params",
                "capabilities",
                "categories",
                "features",
                "maintainers",
                "requires_configuration",
                "readiness",
                "auto_recommended",
                "readiness_reason",
                "source_ref",
                "relevance_score",
            ],
            {"description": 600},
        )
        return _annotate_tool_payload(
            tool_name,
            compact,
            payload_policy="compacted",
            compacted=True,
            compaction_reason="financial_source_catalog_window",
        )

    if tool_name in {"inspect_financial_source", "inspect_rss_source"}:
        return _annotate_tool_payload(
            tool_name,
            result,
            payload_policy="complete",
            compacted=False,
        )

    return result
