"""Safe downloads for files generated by Agent screening tools."""

from __future__ import annotations

import re
from pathlib import Path

from fastapi import HTTPException
from fastapi.responses import FileResponse

from api.v1.endpoints.agent import router

EXPORT_DIR = Path(__file__).resolve().parents[4] / "data" / "exports" / "stock-screening"
FILE_ID_RE = re.compile(r"^(?:stock-screen|atr-volatility)-\d{8}-\d{6}-[0-9a-f]{8}\.csv$")


@router.get("/agent/exports/{file_id}")
async def download_agent_export(file_id: str):
    if not FILE_ID_RE.fullmatch(file_id):
        raise HTTPException(status_code=404, detail="导出文件不存在")
    target = (EXPORT_DIR / file_id).resolve()
    if target.parent != EXPORT_DIR.resolve() or not target.is_file():
        raise HTTPException(status_code=404, detail="导出文件不存在")
    return FileResponse(target, media_type="text/csv; charset=utf-8", filename=file_id)
