"""Notification field metadata group 1."""

from src.notification_routing import ROUTABLE_NOTIFICATION_CHANNELS

_FIELD_DEFINITIONS = {
    "ASTRBOT_TOKEN": {
        "title": "AstrBot Token",
        "description": "Optional AstrBot bearer token.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 48,
    },
    "ASTRBOT_URL": {
        "title": "AstrBot URL",
        "description": "AstrBot webhook endpoint URL.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"item_type": "url", "allowed_schemes": ["http", "https"]},
        "display_order": 47,
    },
    "CUSTOM_WEBHOOK_BEARER_TOKEN": {
        "title": "Custom Webhook Bearer Token",
        "description": "Bearer token for authenticated custom webhooks.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 51,
    },
    "CUSTOM_WEBHOOK_BODY_TEMPLATE": {
        "title": "Custom Webhook Body Template",
        "description": "Optional global JSON body template for custom webhooks. It is rendered before URL auto-detected payloads such as Bark, Slack, or Discord, and must render to a JSON object. Prefer $content_json and $title_json; raw $content and $title are not JSON-escaped and can make the template invalid.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "textarea",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 52,
    },
    "CUSTOM_WEBHOOK_URLS": {
        "title": "Custom Webhook URLs",
        "description": "Comma-separated webhook URLs for custom notifications (DingTalk, Bark, Discord, Slack, etc.).",
        "category": "notification",
        "data_type": "array",
        "ui_control": "textarea",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "help_key": "settings.notification.CUSTOM_WEBHOOK_URLS",
        "examples": [
            "CUSTOM_WEBHOOK_URLS=https://example.com/webhook",
            'CUSTOM_WEBHOOK_BODY_TEMPLATE={"msg_type":"text","content":$content_json}',
        ],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 50,
        "docs": [
            {
                "label": "完整指南：自定义 Webhook",
                "href": "https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#自定义-webhook",
            }
        ],
        "warning_codes": ["json_template_must_render_object"],
    },
    "DINGTALK_APP_KEY": {
        "title": "DingTalk App Key",
        "description": "DingTalk app key.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 20,
    },
    "DINGTALK_APP_SECRET": {
        "title": "DingTalk App Secret",
        "description": "DingTalk app secret.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 30,
    },
    "DISCORD_BOT_TOKEN": {
        "title": "Discord Bot Token",
        "description": "Discord bot token for interactive bot mode.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 34,
        "help_key": "settings.notification.chat_bots",
        "examples": ["DISCORD_BOT_TOKEN=your_discord_bot_token", "DISCORD_MAIN_CHANNEL_ID=123456789012345678"],
        "docs": [
            {
                "label": "完整指南：Discord",
                "href": "https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#discord",
            }
        ],
        "warning_codes": ["secret_value"],
    },
    "DISCORD_INTERACTIONS_PUBLIC_KEY": {
        "title": "Discord Interactions Public Key",
        "description": "Discord public key used to verify inbound interaction/webhook signatures.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 36,
    },
    "DISCORD_MAIN_CHANNEL_ID": {
        "title": "Discord Channel ID",
        "description": "Discord main channel ID for sending messages.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 35,
    },
    "DISCORD_WEBHOOK_URL": {
        "title": "Discord Webhook URL",
        "description": "Discord webhook URL for channel notifications.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 33,
        "help_key": "settings.notification.chat_bots",
        "examples": ["DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/xxx/yyy"],
        "docs": [
            {
                "label": "完整指南：Discord",
                "href": "https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#discord",
            }
        ],
        "warning_codes": ["webhook_secret_value"],
    },
    "EMAIL_PASSWORD": {
        "title": "Email Password",
        "description": "Email password or app-specific authorization code.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 26,
        "help_key": "settings.notification.email",
        "examples": ["EMAIL_PASSWORD=your_smtp_authorization_code"],
        "docs": [
            {
                "label": "完整指南：邮件",
                "href": "https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#邮件",
            }
        ],
        "warning_codes": ["secret_value", "smtp_authorization_code"],
    },
    "EMAIL_RECEIVERS": {
        "title": "Email Receivers",
        "description": "Comma-separated recipient email addresses. Leave empty to send to yourself.",
        "category": "notification",
        "data_type": "array",
        "ui_control": "textarea",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"multi_value": True, "delimiter": ","},
        "display_order": 27,
        "help_key": "settings.notification.email",
        "examples": [
            "EMAIL_RECEIVERS=user1@example.com,user2@example.com",
            "STOCK_GROUP_1=600519,300750",
            "EMAIL_GROUP_1=user1@example.com",
        ],
        "docs": [
            {
                "label": "完整指南：邮件",
                "href": "https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#邮件",
            }
        ],
        "warning_codes": ["comma_separated_values"],
    },
    "EMAIL_SENDER": {
        "title": "Email Sender",
        "description": "Sender email address (SMTP host auto-detected).",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 25,
        "help_key": "settings.notification.email",
        "examples": [
            "EMAIL_SENDER=sender@example.com",
            "EMAIL_PASSWORD=your_smtp_authorization_code",
            "EMAIL_RECEIVERS=user1@example.com,user2@example.com",
        ],
        "docs": [
            {
                "label": "完整指南：邮件",
                "href": "https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#邮件",
            }
        ],
        "warning_codes": [],
    },
    "FEISHU_APP_ID": {
        "title": "Feishu App ID",
        "description": "Feishu app bot App ID for app/stream bot mode or cloud documents. It does not enable group webhook push by itself.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 15,
    },
    "FEISHU_APP_SECRET": {
        "title": "Feishu App Secret",
        "description": "Feishu app bot App Secret for app/stream bot mode or cloud documents. It does not enable group webhook push by itself.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 16,
    },
    "FEISHU_WEBHOOK_KEYWORD": {
        "title": "Feishu Webhook Keyword",
        "description": "Optional keyword required by Feishu custom bot security settings. The sender prepends it to every webhook message.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 14,
    },
    "FEISHU_WEBHOOK_SECRET": {
        "title": "Feishu Webhook Secret",
        "description": "Optional signing secret from Feishu custom bot security settings. Only used for webhook push mode.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 13,
    },
    "FEISHU_WEBHOOK_URL": {
        "title": "Feishu Webhook URL",
        "description": "Feishu custom bot webhook URL for group notifications. This is the webhook push channel; FEISHU_APP_ID / FEISHU_APP_SECRET do not enable webhook delivery by themselves.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"item_type": "url", "allowed_schemes": ["http", "https"]},
        "display_order": 12,
        "help_key": "settings.notification.FEISHU_WEBHOOK_URL",
        "examples": [
            "FEISHU_WEBHOOK_URL=https://open.feishu.cn/open-apis/bot/v2/hook/your_hook_token",
            "FEISHU_WEBHOOK_SECRET=your_feishu_webhook_secret",
            "FEISHU_WEBHOOK_KEYWORD=股票日报",
        ],
        "docs": [
            {
                "label": "完整指南：飞书通知配置",
                "href": "https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#飞书",
            },
            {
                "label": "飞书机器人配置专题",
                "href": "https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/bot/feishu-bot-config.md",
            },
        ],
        "warning_codes": ["feishu_webhook_not_app_secret"],
    },
    "GOTIFY_TOKEN": {
        "title": "Gotify Token",
        "description": "Gotify application token sent via the X-Gotify-Key header.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 47,
    },
    "GOTIFY_URL": {
        "title": "Gotify URL",
        "description": "Gotify server base URL. Do not include /message; the sender appends it.",
        "category": "notification",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"item_type": "url", "allowed_schemes": ["http", "https"]},
        "display_order": 46,
    },
    "MERGE_EMAIL_NOTIFICATION": {
        "title": "Merge Email Notification",
        "description": "Merge stock analysis and market review into a single email notification.",
        "category": "notification",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 61,
    },
    "NOTIFICATION_ALERT_CHANNELS": {
        "title": "Alert Notification Channels",
        "description": "Comma-separated route for event alert notifications. Empty keeps all configured channels.",
        "category": "notification",
        "data_type": "array",
        "ui_control": "textarea",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "",
        "options": [{"label": "wechat", "value": "wechat"}],
        "validation": {"allowed_values": ["wechat"], "delimiter": ","},
        "display_order": 63,
    },
    "NOTIFICATION_COOLDOWN_SECONDS": {
        "title": "Notification Cooldown Seconds",
        "description": "Suppress repeated static notifications with the same cooldown key during this window. 0 disables cooldown.",
        "category": "notification",
        "data_type": "integer",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0",
        "options": [],
        "validation": {"min": 0},
        "display_order": 66,
    },
}
