# -*- coding: utf-8 -*-
"""Field metadata for the AI Model category."""

from __future__ import annotations
from typing import Any, Dict


_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    'AIHUBMIX_KEY': {
        'title': 'AIHubmix Key',
        'description': 'AIHubmix one-stop API key – access all mainstream models with a single key, no VPN required. Auto-sets base URL to aihubmix.com/v1. Get key: https://aihubmix.com/?aff=CfMq',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 5,
        'help_key': 'settings.ai_model.provider_keys',
        'examples': ['AIHUBMIX_KEY=sk-xxxx'],
        'docs': [{'label': 'LLM 配置指南', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md'}, {'label': 'LLM 服务商配置速查', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md'}],
        'warning_codes': ['secret_value'],
    },
    'ANSPIRE_LLM_BASE_URL': {
        'title': 'Anspire LLM Base URL',
        'description': 'Anspire OpenAI-compatible gateway. Default: https://open-gateway.anspire.cn/v6; global endpoint: https://open-gateway.anspire.ai/v6.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'https://open-gateway.anspire.cn/v6',
        'options': [],
        'validation': {'format': 'url'},
        'display_order': 7,
    },
    'ANSPIRE_LLM_ENABLED': {
        'title': 'Anspire LLM Enabled',
        'description': 'Use ANSPIRE_API_KEYS as an OpenAI-compatible Anspire LLM key when no higher-priority LLM channel or OpenAI-compatible key is configured.',
        'category': 'ai_model',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'true',
        'options': [],
        'validation': {},
        'display_order': 6,
    },
    'ANSPIRE_LLM_MODEL': {
        'title': 'Anspire LLM Model',
        'description': 'Default model used when ANSPIRE_API_KEYS enables the Anspire LLM gateway without an explicit LITELLM_MODEL.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'Doubao-Seed-2.0-lite',
        'options': [],
        'validation': {},
        'display_order': 8,
    },
    'ANTHROPIC_API_KEY': {
        'title': 'Anthropic API Key',
        'description': 'Anthropic Claude API key (from https://console.anthropic.com).',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 35,
        'help_key': 'settings.ai_model.provider_keys',
        'examples': ['ANTHROPIC_API_KEY=sk-ant-xxxx', 'LITELLM_MODEL=anthropic/claude-sonnet-4-6'],
        'docs': [{'label': 'LLM 配置指南', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md'}, {'label': 'LLM 服务商配置速查', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md'}],
        'warning_codes': ['secret_value'],
    },
    'ANTHROPIC_API_KEYS': {
        'title': 'Anthropic API Keys (Multi)',
        'description': 'Comma-separated Anthropic API keys for load balancing. Takes priority over ANTHROPIC_API_KEY.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 35,
    },
    'ANTHROPIC_BASE_URL': {
        'title': 'Anthropic Base URL',
        'description': 'Anthropic API 自定义网关地址（用于代理 / 中转 / Claude Code 兼容服务）。',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'format': 'url'},
        'display_order': 100,
    },
    'ANTHROPIC_AUTH_TOKEN': {
        'title': 'Anthropic Auth Token',
        'description': 'Anthropic 自定义网关 / Claude Code 兼容服务的鉴权 token。',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 101,
        'warning_codes': ['secret_value'],
    },
    'ANTHROPIC_MAX_TOKENS': {
        'title': 'Anthropic Max Tokens',
        'description': 'Anthropic API 响应最大 token 数（默认 8192）。',
        'category': 'ai_model',
        'data_type': 'number',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '8192',
        'options': [],
        'validation': {'min': 256, 'max': 8192},
        'display_order': 38,
    },
    'ANTHROPIC_MODEL': {
        'title': 'Anthropic Model',
        'description': 'Claude 模型名称（如 claude-sonnet-4-6）。',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'claude-sonnet-4-6',
        'options': [],
        'validation': {},
        'display_order': 36,
    },
    'ANTHROPIC_TEMPERATURE': {
        'title': 'Anthropic Temperature',
        'description': '温度参数，范围 [0.0, 1.0]。',
        'category': 'ai_model',
        'data_type': 'number',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '0.7',
        'options': [],
        'validation': {'min': 0.0, 'max': 1.0},
        'display_order': 37,
    },
    'DEEPSEEK_API_KEY': {
        'title': 'DeepSeek API Key',
        'description': 'Official DeepSeek API key (from https://platform.deepseek.com). For compatibility, a key set alone still auto-infers deepseek/deepseek-chat and logs a deprecation warning; new configs should migrate to deepseek/deepseek-v4-flash. Also works in multi-channel mode.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 6,
        'help_key': 'settings.ai_model.provider_keys',
        'examples': ['DEEPSEEK_API_KEY=sk-xxxx', 'LITELLM_MODEL=deepseek/deepseek-v4-flash'],
        'docs': [{'label': 'LLM 配置指南', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md'}, {'label': 'LLM 服务商配置速查', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md'}],
        'warning_codes': ['secret_value'],
    },
    'DEEPSEEK_API_KEYS': {
        'title': 'DeepSeek API Keys (Multi)',
        'description': 'Comma-separated DeepSeek API keys for load balancing. Takes priority over DEEPSEEK_API_KEY.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 7,
    },
    'GEMINI_API_KEY': {
        'title': 'Gemini API Key',
        'description': 'Single API key for Gemini service (from https://aistudio.google.com).',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 10,
        'help_key': 'settings.ai_model.provider_keys',
        'examples': ['GEMINI_API_KEY=your_gemini_api_key', 'LITELLM_MODEL=gemini/gemini-3.1-pro-preview'],
        'docs': [{'label': 'LLM 配置指南', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md'}, {'label': 'LLM 服务商配置速查', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md'}],
        'warning_codes': ['secret_value'],
    },
    'GEMINI_API_KEYS': {
        'title': 'Gemini API Keys (Multi)',
        'description': 'Comma-separated Gemini API keys for load balancing. Takes priority over GEMINI_API_KEY.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 11,
    },
    'GEMINI_MODEL': {
        'title': 'Gemini Model',
        'description': 'Gemini model name.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'gemini-3.1-pro-preview',
        'options': [],
        'validation': {},
        'display_order': 20,
    },
    'GEMINI_MODEL_FALLBACK': {
        'title': 'Gemini Fallback Model',
        'description': 'Fallback Gemini model name (used when LITELLM_FALLBACK_MODELS is not set and primary is Gemini).',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'gemini-3-flash-preview',
        'options': [],
        'validation': {},
        'display_order': 21,
    },
    'GEMINI_TEMPERATURE': {
        'title': 'Gemini Temperature',
        'description': 'Temperature in range [0.0, 2.0].',
        'category': 'ai_model',
        'data_type': 'number',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '0.7',
        'options': [],
        'validation': {'min': 0.0, 'max': 2.0},
        'display_order': 30,
    },
    'LITELLM_CONFIG': {
        'title': 'Advanced Model Routing Config',
        'description': 'Path to an advanced model routing YAML file (expert use). When valid/parseable and yields a model_list, it takes priority over channels and legacy keys; otherwise channels/legacy are used as fallback.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 3,
        'help_key': 'settings.ai_model.LITELLM_CONFIG',
        'examples': ['LITELLM_CONFIG=./litellm_config.yaml'],
        'docs': [{'label': 'LLM 配置指南：YAML 模式', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md#方式三litellm-原生-yaml-配置适合专家或复杂路由'}],
        'warning_codes': ['yaml_config_overrides_channel_editor'],
    },
    'LITELLM_FALLBACK_MODELS': {
        'title': 'Fallback Models',
        'description': 'Comma-separated fallback models tried when the primary model fails (e.g. anthropic/claude-sonnet-4-6,openai/gpt-5.4-mini). Useful for cross-provider redundancy.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 2,
        'help_key': 'settings.ai_model.LITELLM_FALLBACK_MODELS',
        'examples': ['LITELLM_FALLBACK_MODELS=deepseek/deepseek-v4-pro,gemini/gemini-3-flash-preview', 'LITELLM_FALLBACK_MODELS=openai/gpt-5.4-mini'],
        'docs': [{'label': 'LLM 配置指南', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md'}, {'label': '完整指南：AI 模型配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#ai-模型配置'}],
        'warning_codes': ['fallback_models_must_be_available'],
    },
    'LITELLM_MODEL': {
        'title': 'Primary Model',
        'description': 'Primary model in provider/model format (e.g. gemini/gemini-3.1-pro-preview, deepseek/deepseek-v4-flash, anthropic/claude-sonnet-4-6). If empty, it is auto-inferred from available API keys or channel declarations.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 1,
        'help_key': 'settings.ai_model.LITELLM_MODEL',
        'examples': ['LITELLM_MODEL=deepseek/deepseek-v4-flash', 'LITELLM_MODEL=gemini/gemini-3.1-pro-preview', 'LITELLM_MODEL=ollama/qwen3:8b'],
        'docs': [{'label': 'LLM 配置指南', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md'}, {'label': '完整指南：AI 模型配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#ai-模型配置'}],
        'warning_codes': ['provider_prefix_required'],
    },
    'LLM_CHANNELS': {
        'title': 'LLM Channels',
        'description': 'Channel names (comma-separated). Managed by the channel editor above.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 4,
        'help_key': 'settings.ai_model.LLM_CHANNELS',
        'examples': ['LLM_CHANNELS=deepseek,aihubmix', 'LLM_DEEPSEEK_BASE_URL=https://api.deepseek.com', 'LLM_DEEPSEEK_API_KEY=sk-xxxx', 'LLM_DEEPSEEK_MODELS=deepseek-v4-flash,deepseek-v4-pro'],
        'docs': [{'label': 'LLM 配置指南：渠道模式', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md#方式二渠道channels模式配置适合进阶多模型'}, {'label': 'LLM 服务商配置速查', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md'}],
        'warning_codes': ['channels_override_legacy_keys'],
    },
    'LLM_REASONING_EFFORT': {
        'title': 'Reasoning Effort',
        'description': "Controls reasoning depth for thinking-capable models. 'auto' uses provider defaults. Only effective when Thinking Mode is enabled.",
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'select',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'auto',
        'options': [{'label': 'Auto (Default)', 'value': 'auto'}, {'label': 'Low', 'value': 'low'}, {'label': 'Medium', 'value': 'medium'}, {'label': 'High', 'value': 'high'}],
        'validation': {'enum': ['auto', 'low', 'medium', 'high']},
        'display_order': 7,
        'examples': ['LLM_REASONING_EFFORT=high'],
        'warning_codes': [],
    },
    'LLM_TEMPERATURE': {
        'title': 'Temperature',
        'description': 'Unified sampling temperature for all LLM calls. Range [0.0, 2.0], default 0.7.',
        'category': 'ai_model',
        'data_type': 'number',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '0.7',
        'options': [],
        'validation': {'min': 0.0, 'max': 2.0},
        'display_order': 5,
        'help_key': 'settings.ai_model.LLM_TEMPERATURE',
        'examples': ['LLM_TEMPERATURE=0.2', 'LLM_TEMPERATURE=0.7'],
        'docs': [{'label': '完整指南：AI 模型配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#ai-模型配置'}],
        'warning_codes': [],
    },
    'LLM_THINKING_ENABLED': {
        'title': 'Thinking Mode',
        'description': 'Enable extended thinking mode for supported models. The model will produce deeper reasoning traces.',
        'category': 'ai_model',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'false',
        'options': [],
        'validation': {},
        'display_order': 6,
        'examples': ['LLM_THINKING_ENABLED=true'],
        'warning_codes': [],
    },
    'OPENAI_API_KEY': {
        'title': 'OpenAI API Key',
        'description': 'API key for OpenAI-compatible service.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 40,
        'help_key': 'settings.ai_model.provider_keys',
        'examples': ['OPENAI_API_KEY=sk-xxxx', 'OPENAI_BASE_URL=https://api.example.com/v1', 'LITELLM_MODEL=openai/gpt-5.5'],
        'docs': [{'label': 'LLM 配置指南', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md'}, {'label': 'LLM 服务商配置速查', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md'}],
        'warning_codes': ['secret_value'],
    },
    'OPENAI_API_KEYS': {
        'title': 'OpenAI API Keys (Multi)',
        'description': 'Comma-separated OpenAI-compatible API keys for load balancing. Takes priority over AIHUBMIX_KEY and OPENAI_API_KEY.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 41,
    },
    'OPENAI_BASE_URL': {
        'title': 'OpenAI Base URL',
        'description': 'Base URL for OpenAI-compatible endpoint.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 50,
        'help_key': 'settings.ai_model.OPENAI_BASE_URL',
        'examples': ['OPENAI_BASE_URL=https://api.openai.com/v1', 'OPENAI_BASE_URL=https://api.example.com/v1'],
        'docs': [{'label': 'LLM 配置指南', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/LLM_CONFIG_GUIDE.md'}, {'label': 'LLM 服务商配置速查', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/llm-providers.md'}],
        'warning_codes': ['base_url_must_match_provider'],
    },
    'OPENAI_MODEL': {
        'title': 'OpenAI Model',
        'description': 'Model name for OpenAI-compatible endpoint.',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'gpt-5.5',
        'options': [],
        'validation': {},
        'display_order': 60,
    },
    'OPENAI_TEMPERATURE': {
        'title': 'OpenAI Temperature',
        'description': 'Temperature for OpenAI-compatible models in range [0.0, 2.0].',
        'category': 'ai_model',
        'data_type': 'number',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '0.7',
        'options': [],
        'validation': {'min': 0.0, 'max': 2.0},
        'display_order': 62,
    },
    'CLAUDE_CODE_AUTO_COMPACT_WINDOW': {
        'title': 'Claude Code Auto Compact Window',
        'description': 'Claude Code CLI 自动压缩上下文窗口的 token 阈值；超过该值时自动调用 /compact。',
        'category': 'ai_model',
        'data_type': 'number',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '1000000',
        'options': [],
        'validation': {'min': 1000},
        'display_order': 102,
    },
    'ANTHROPIC_DEFAULT_SONNET_MODEL': {
        'title': 'Anthropic Default Sonnet Model',
        'description': 'Claude Code Sonnet 槽位的默认模型（ANTHROPIC_DEFAULT_SONNET_MODEL）。',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 103,
    },
    'ANTHROPIC_DEFAULT_OPUS_MODEL': {
        'title': 'Anthropic Default Opus Model',
        'description': 'Claude Code Opus 槽位的默认模型（ANTHROPIC_DEFAULT_OPUS_MODEL）。',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 104,
    },
    'ANTHROPIC_DEFAULT_HAIKU_MODEL': {
        'title': 'Anthropic Default Haiku Model',
        'description': 'Claude Code Haiku 槽位的默认模型（ANTHROPIC_DEFAULT_HAIKU_MODEL）。',
        'category': 'ai_model',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 105,
    },
}

