# -*- coding: utf-8 -*-
"""Field metadata for the AI Model category."""

from __future__ import annotations
from typing import Any, Dict


_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "ANTHROPIC_BASE_URL": {
        "title": "Anthropic Base URL",
        "description": "Anthropic API 自定义网关地址（用于代理 / 中转 / Claude Code 兼容服务）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {"format": "url"},
        "display_order": 100,
    },
    "ANTHROPIC_AUTH_TOKEN": {
        "title": "Anthropic Auth Token",
        "description": "Anthropic 自定义网关 / Claude Code 兼容服务的鉴权 token。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "password",
        "is_sensitive": True,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 101,
        "warning_codes": ["secret_value"],
    },
    "ANTHROPIC_MODEL": {
        "title": "Anthropic Model",
        "description": "Claude 模型名称（如 claude-sonnet-4-6）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "claude-sonnet-4-6",
        "options": [],
        "validation": {},
        "display_order": 36,
    },
    "LLM_REASONING_EFFORT": {
        "title": "Reasoning Effort",
        "description": "Controls reasoning depth for thinking-capable models. 'auto' uses provider defaults. Only effective when Thinking Mode is enabled.",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "select",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "auto",
        "options": [
            {"label": "Auto (Default)", "value": "auto"},
            {"label": "Low", "value": "low"},
            {"label": "Medium", "value": "medium"},
            {"label": "High", "value": "high"},
        ],
        "validation": {"enum": ["auto", "low", "medium", "high"]},
        "display_order": 7,
        "examples": ["LLM_REASONING_EFFORT=high"],
        "warning_codes": [],
    },
    "LLM_TEMPERATURE": {
        "title": "Temperature",
        "description": "Unified sampling temperature for all LLM calls. Range [0.0, 2.0], default 0.7.",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "0.7",
        "options": [],
        "validation": {"min": 0.0, "max": 2.0},
        "display_order": 5,
        "help_key": "settings.ai_model.LLM_TEMPERATURE",
        "examples": ["LLM_TEMPERATURE=0.2", "LLM_TEMPERATURE=0.7"],
        "docs": [
            {
                "label": "完整指南：AI 模型配置",
                "href": "https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#ai-模型配置",
            }
        ],
        "warning_codes": [],
    },
    "LLM_THINKING_ENABLED": {
        "title": "Thinking Mode",
        "description": "Enable extended thinking mode for supported models. The model will produce deeper reasoning traces.",
        "category": "ai_model",
        "data_type": "boolean",
        "ui_control": "switch",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "false",
        "options": [],
        "validation": {},
        "display_order": 6,
        "examples": ["LLM_THINKING_ENABLED=true"],
        "warning_codes": [],
    },
    "CLAUDE_CODE_AUTO_COMPACT_WINDOW": {
        "title": "Claude Code Auto Compact Window",
        "description": "Claude Code CLI 自动压缩上下文窗口的 token 阈值；超过该值时自动调用 /compact。",
        "category": "ai_model",
        "data_type": "number",
        "ui_control": "number",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": "1000000",
        "options": [],
        "validation": {"min": 1000},
        "display_order": 102,
    },
    "ANTHROPIC_DEFAULT_SONNET_MODEL": {
        "title": "Anthropic Default Sonnet Model",
        "description": "Claude Code Sonnet 槽位的默认模型（ANTHROPIC_DEFAULT_SONNET_MODEL）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 103,
    },
    "ANTHROPIC_DEFAULT_OPUS_MODEL": {
        "title": "Anthropic Default Opus Model",
        "description": "Claude Code Opus 槽位的默认模型（ANTHROPIC_DEFAULT_OPUS_MODEL）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 104,
    },
    "ANTHROPIC_DEFAULT_HAIKU_MODEL": {
        "title": "Anthropic Default Haiku Model",
        "description": "Claude Code Haiku 槽位的默认模型（ANTHROPIC_DEFAULT_HAIKU_MODEL）。",
        "category": "ai_model",
        "data_type": "string",
        "ui_control": "text",
        "is_sensitive": False,
        "is_required": False,
        "is_editable": True,
        "default_value": None,
        "options": [],
        "validation": {},
        "display_order": 105,
    },
}
