# -*- coding: utf-8 -*-
"""Field metadata for the Data Source category."""

from __future__ import annotations
from typing import Any, Dict


_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    'ANSPIRE_API_KEYS': {
        'title': 'Anspire API Keys',
        'description': 'Comma-separated Anspire Open API keys. Used by Anspire Search and, by default, the Anspire OpenAI-compatible LLM gateway.',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 22,
        'help_key': 'settings.data_source.search_api_keys',
        'examples': ['ANSPIRE_API_KEYS=key1,key2'],
        'docs': [{'label': '完整指南：搜索服务配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置'}],
        'warning_codes': ['secret_value', 'comma_separated_keys'],
    },
    'BIAS_THRESHOLD': {
        'title': 'Bias Threshold (%)',
        'description': "Deviation threshold from MA5 (%). Exceeding this triggers 'do not chase' warning. Strong trend stocks auto-widen to 1.5x.",
        'category': 'data_source',
        'data_type': 'number',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '5.0',
        'options': [],
        'validation': {'min': 0.0, 'max': 50.0},
        'display_order': 62,
    },
    'BOCHA_API_KEYS': {
        'title': 'Bocha API Keys',
        'description': 'Comma-separated Bocha Search API keys.',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 51,
    },
    'BRAVE_API_KEYS': {
        'title': 'Brave API Keys',
        'description': 'Comma-separated Brave Search API keys.',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 50,
    },
    'ENABLE_CHIP_DISTRIBUTION': {
        'title': 'Enable Chip Distribution',
        'description': 'Enable chip distribution analysis. May be unstable; recommended to disable on cloud deployments.',
        'category': 'data_source',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'true',
        'options': [],
        'validation': {},
        'display_order': 23,
        'help_key': 'settings.data_source.ENABLE_CHIP_DISTRIBUTION',
        'examples': ['ENABLE_CHIP_DISTRIBUTION=true', 'ENABLE_CHIP_DISTRIBUTION=false'],
        'docs': [{'label': '完整指南：数据源配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置'}],
        'warning_codes': ['cloud_deployments_may_disable'],
    },
    'ENABLE_REALTIME_QUOTE': {
        'title': 'Enable Realtime Quote',
        'description': 'Enable realtime market quotes. Disable to only use historical close prices.',
        'category': 'data_source',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'true',
        'options': [],
        'validation': {},
        'display_order': 22,
        'help_key': 'settings.data_source.realtime_quotes',
        'examples': ['ENABLE_REALTIME_QUOTE=true', 'ENABLE_REALTIME_QUOTE=false'],
        'docs': [{'label': '完整指南：数据源配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置'}],
        'warning_codes': [],
    },
    'ENABLE_REALTIME_TECHNICAL_INDICATORS': {
        'title': 'Realtime Technical Indicators',
        'description': 'Use intraday realtime price for MA5/MA10/MA20 and trend analysis (Issue #234). Disable to use yesterday close.',
        'category': 'data_source',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'true',
        'options': [],
        'validation': {},
        'display_order': 21,
        'help_key': 'settings.data_source.realtime_quotes',
        'examples': ['ENABLE_REALTIME_TECHNICAL_INDICATORS=true', 'ENABLE_REALTIME_TECHNICAL_INDICATORS=false'],
        'docs': [{'label': '完整指南：数据源配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#数据源配置'}],
        'warning_codes': [],
    },
    'MINIMAX_API_KEYS': {
        'title': 'MiniMax API Key',
        'description': 'MiniMax API key (search priority: Bocha > Tavily > Brave > SerpAPI > MiniMax > SearXNG).',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 53,
    },
    'NEWS_MAX_AGE_DAYS': {
        'title': 'News Max Age (Days)',
        'description': 'Maximum age of news in days. Older articles are excluded from analysis context.',
        'category': 'data_source',
        'data_type': 'integer',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '3',
        'options': [],
        'validation': {'min': 1, 'max': 30},
        'display_order': 60,
        'help_key': 'settings.data_source.news_window',
        'examples': ['NEWS_MAX_AGE_DAYS=3', 'NEWS_STRATEGY_PROFILE=short'],
        'docs': [{'label': '完整指南：环境变量完整列表', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表'}],
        'warning_codes': [],
    },
    'NEWS_STRATEGY_PROFILE': {
        'title': 'News Strategy Profile',
        'description': 'News window profile: ultra_short(1d), short(3d), medium(7d), long(30d). Effective window = min(profile, NEWS_MAX_AGE_DAYS).',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'select',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'short',
        'options': ['ultra_short', 'short', 'medium', 'long'],
        'validation': {'enum': ['ultra_short', 'short', 'medium', 'long']},
        'display_order': 61,
        'help_key': 'settings.data_source.news_window',
        'examples': ['NEWS_STRATEGY_PROFILE=short', 'NEWS_MAX_AGE_DAYS=3'],
        'docs': [{'label': '完整指南：环境变量完整列表', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表'}],
        'warning_codes': [],
    },
    'PYTDX_HOST': {
        'title': 'Pytdx Host',
        'description': 'Tongdaxin data server IP. Used with PYTDX_PORT. Overrides built-in defaults.',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 55,
    },
    'PYTDX_PORT': {
        'title': 'Pytdx Port',
        'description': 'Tongdaxin data server port (e.g. 7709). Used with PYTDX_HOST.',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 56,
    },
    'PYTDX_SERVERS': {
        'title': 'Pytdx Servers',
        'description': 'Comma-separated ip:port (e.g. 192.168.1.1:7709,10.0.0.1:7709). Overrides PYTDX_HOST+PYTDX_PORT.',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 57,
    },
    'SEARXNG_BASE_URLS': {
        'title': 'SearXNG Base URLs',
        'description': 'Comma-separated SearXNG instance URLs (self-hosted, no quota). Enable format: json in settings.yml.',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ',', 'item_type': 'url', 'allowed_schemes': ['http', 'https']},
        'display_order': 52,
        'help_key': 'settings.data_source.SEARXNG_BASE_URLS',
        'examples': ['SEARXNG_BASE_URLS=https://search.example.com', 'SEARXNG_PUBLIC_INSTANCES_ENABLED=false'],
        'docs': [{'label': '完整指南：搜索服务配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置'}],
        'warning_codes': ['requires_json_format'],
    },
    'SEARXNG_PUBLIC_INSTANCES_ENABLED': {
        'title': 'SearXNG Public Instances',
        'description': 'Auto-discover public SearXNG instances from searx.space when SEARXNG_BASE_URLS is empty. Default: true; set false to disable.',
        'category': 'data_source',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'true',
        'options': [],
        'validation': {},
        'display_order': 53,
    },
    'SERPAPI_API_KEYS': {
        'title': 'SerpAPI Keys',
        'description': 'Comma-separated SerpAPI keys.',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 40,
    },
    'TAVILY_API_KEYS': {
        'title': 'Tavily API Keys',
        'description': 'Comma-separated Tavily API keys.',
        'category': 'data_source',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 30,
        'help_key': 'settings.data_source.search_api_keys',
        'examples': ['TAVILY_API_KEYS=tvly-xxxx', 'TAVILY_API_KEYS=tvly-key-1,tvly-key-2'],
        'docs': [{'label': '完整指南：搜索服务配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#搜索服务配置'}],
        'warning_codes': ['secret_value', 'comma_separated_keys'],
    },
}

