# -*- coding: utf-8 -*-
"""Field metadata for the Notification category."""

from __future__ import annotations

from typing import Any, Dict, List

from src.notification_routing import ROUTABLE_NOTIFICATION_CHANNELS

NOTIFICATION_SEVERITIES = ("info", "warning", "error", "critical")


_FIELD_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    'ASTRBOT_TOKEN': {
        'title': 'AstrBot Token',
        'description': 'Optional AstrBot bearer token.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 48,
    },
    'ASTRBOT_URL': {
        'title': 'AstrBot URL',
        'description': 'AstrBot webhook endpoint URL.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'item_type': 'url', 'allowed_schemes': ['http', 'https']},
        'display_order': 47,
    },
    'CUSTOM_WEBHOOK_BEARER_TOKEN': {
        'title': 'Custom Webhook Bearer Token',
        'description': 'Bearer token for authenticated custom webhooks.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 51,
    },
    'CUSTOM_WEBHOOK_BODY_TEMPLATE': {
        'title': 'Custom Webhook Body Template',
        'description': 'Optional global JSON body template for custom webhooks. It is rendered before URL auto-detected payloads such as Bark, Slack, or Discord, and must render to a JSON object. Prefer $content_json and $title_json; raw $content and $title are not JSON-escaped and can make the template invalid.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'textarea',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 52,
    },
    'CUSTOM_WEBHOOK_URLS': {
        'title': 'Custom Webhook URLs',
        'description': 'Comma-separated webhook URLs for custom notifications (DingTalk, Bark, Discord, Slack, etc.).',
        'category': 'notification',
        'data_type': 'array',
        'ui_control': 'textarea',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'help_key': 'settings.notification.CUSTOM_WEBHOOK_URLS',
        'examples': ['CUSTOM_WEBHOOK_URLS=https://example.com/webhook', 'CUSTOM_WEBHOOK_BODY_TEMPLATE={"msg_type":"text","content":$content_json}'],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 50,
        'docs': [{'label': '完整指南：自定义 Webhook', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#自定义-webhook'}],
        'warning_codes': ['json_template_must_render_object'],
    },
    'DINGTALK_APP_KEY': {
        'title': 'DingTalk App Key',
        'description': 'DingTalk app key.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 20,
    },
    'DINGTALK_APP_SECRET': {
        'title': 'DingTalk App Secret',
        'description': 'DingTalk app secret.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 30,
    },
    'DISCORD_BOT_TOKEN': {
        'title': 'Discord Bot Token',
        'description': 'Discord bot token for interactive bot mode.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 34,
        'help_key': 'settings.notification.chat_bots',
        'examples': ['DISCORD_BOT_TOKEN=your_discord_bot_token', 'DISCORD_MAIN_CHANNEL_ID=123456789012345678'],
        'docs': [{'label': '完整指南：Discord', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#discord'}],
        'warning_codes': ['secret_value'],
    },
    'DISCORD_INTERACTIONS_PUBLIC_KEY': {
        'title': 'Discord Interactions Public Key',
        'description': 'Discord public key used to verify inbound interaction/webhook signatures.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 36,
    },
    'DISCORD_MAIN_CHANNEL_ID': {
        'title': 'Discord Channel ID',
        'description': 'Discord main channel ID for sending messages.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 35,
    },
    'DISCORD_WEBHOOK_URL': {
        'title': 'Discord Webhook URL',
        'description': 'Discord webhook URL for channel notifications.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 33,
        'help_key': 'settings.notification.chat_bots',
        'examples': ['DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/xxx/yyy'],
        'docs': [{'label': '完整指南：Discord', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#discord'}],
        'warning_codes': ['webhook_secret_value'],
    },
    'EMAIL_PASSWORD': {
        'title': 'Email Password',
        'description': 'Email password or app-specific authorization code.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 26,
        'help_key': 'settings.notification.email',
        'examples': ['EMAIL_PASSWORD=your_smtp_authorization_code'],
        'docs': [{'label': '完整指南：邮件', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#邮件'}],
        'warning_codes': ['secret_value', 'smtp_authorization_code'],
    },
    'EMAIL_RECEIVERS': {
        'title': 'Email Receivers',
        'description': 'Comma-separated recipient email addresses. Leave empty to send to yourself.',
        'category': 'notification',
        'data_type': 'array',
        'ui_control': 'textarea',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'multi_value': True, 'delimiter': ','},
        'display_order': 27,
        'help_key': 'settings.notification.email',
        'examples': ['EMAIL_RECEIVERS=user1@example.com,user2@example.com', 'STOCK_GROUP_1=600519,300750', 'EMAIL_GROUP_1=user1@example.com'],
        'docs': [{'label': '完整指南：邮件', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#邮件'}],
        'warning_codes': ['comma_separated_values'],
    },
    'EMAIL_SENDER': {
        'title': 'Email Sender',
        'description': 'Sender email address (SMTP host auto-detected).',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 25,
        'help_key': 'settings.notification.email',
        'examples': ['EMAIL_SENDER=sender@example.com', 'EMAIL_PASSWORD=your_smtp_authorization_code', 'EMAIL_RECEIVERS=user1@example.com,user2@example.com'],
        'docs': [{'label': '完整指南：邮件', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#邮件'}],
        'warning_codes': [],
    },
    'FEISHU_APP_ID': {
        'title': 'Feishu App ID',
        'description': 'Feishu app bot App ID for app/stream bot mode or cloud documents. It does not enable group webhook push by itself.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 15,
    },
    'FEISHU_APP_SECRET': {
        'title': 'Feishu App Secret',
        'description': 'Feishu app bot App Secret for app/stream bot mode or cloud documents. It does not enable group webhook push by itself.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 16,
    },
    'FEISHU_WEBHOOK_KEYWORD': {
        'title': 'Feishu Webhook Keyword',
        'description': 'Optional keyword required by Feishu custom bot security settings. The sender prepends it to every webhook message.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 14,
    },
    'FEISHU_WEBHOOK_SECRET': {
        'title': 'Feishu Webhook Secret',
        'description': 'Optional signing secret from Feishu custom bot security settings. Only used for webhook push mode.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 13,
    },
    'FEISHU_WEBHOOK_URL': {
        'title': 'Feishu Webhook URL',
        'description': 'Feishu custom bot webhook URL for group notifications. This is the webhook push channel; FEISHU_APP_ID / FEISHU_APP_SECRET do not enable webhook delivery by themselves.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'item_type': 'url', 'allowed_schemes': ['http', 'https']},
        'display_order': 12,
        'help_key': 'settings.notification.FEISHU_WEBHOOK_URL',
        'examples': ['FEISHU_WEBHOOK_URL=https://open.feishu.cn/open-apis/bot/v2/hook/your_hook_token', 'FEISHU_WEBHOOK_SECRET=your_feishu_webhook_secret', 'FEISHU_WEBHOOK_KEYWORD=股票日报'],
        'docs': [{'label': '完整指南：飞书通知配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#飞书'}, {'label': '飞书机器人配置专题', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/bot/feishu-bot-config.md'}],
        'warning_codes': ['feishu_webhook_not_app_secret'],
    },
    'GOTIFY_TOKEN': {
        'title': 'Gotify Token',
        'description': 'Gotify application token sent via the X-Gotify-Key header.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 47,
    },
    'GOTIFY_URL': {
        'title': 'Gotify URL',
        'description': 'Gotify server base URL. Do not include /message; the sender appends it.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'item_type': 'url', 'allowed_schemes': ['http', 'https']},
        'display_order': 46,
    },
    'MERGE_EMAIL_NOTIFICATION': {
        'title': 'Merge Email Notification',
        'description': 'Merge stock analysis and market review into a single email notification.',
        'category': 'notification',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'false',
        'options': [],
        'validation': {},
        'display_order': 61,
    },
    'NOTIFICATION_ALERT_CHANNELS': {
        'title': 'Alert Notification Channels',
        'description': 'Comma-separated route for event alert notifications. Empty keeps all configured channels.',
        'category': 'notification',
        'data_type': 'array',
        'ui_control': 'textarea',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '',
        'options': [{'label': 'wechat', 'value': 'wechat'}],
        'validation': {'allowed_values': ['wechat'], 'delimiter': ','},
        'display_order': 63,
    },
    'NOTIFICATION_COOLDOWN_SECONDS': {
        'title': 'Notification Cooldown Seconds',
        'description': 'Suppress repeated static notifications with the same cooldown key during this window. 0 disables cooldown.',
        'category': 'notification',
        'data_type': 'integer',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '0',
        'options': [],
        'validation': {'min': 0},
        'display_order': 66,
    },
    'NOTIFICATION_DAILY_DIGEST_ENABLED': {
        'title': 'Notification Daily Digest Enabled (Reserved)',
        'description': 'Reserved P4 flag. It is visible for compatibility but does not send daily digests yet.',
        'category': 'notification',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'false',
        'options': [],
        'validation': {},
        'display_order': 70,
    },
    'NOTIFICATION_DEDUP_TTL_SECONDS': {
        'title': 'Notification Dedup TTL Seconds',
        'description': 'Suppress duplicate static notifications with the same dedup key within this TTL. 0 disables deduplication.',
        'category': 'notification',
        'data_type': 'integer',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '0',
        'options': [],
        'validation': {'min': 0},
        'display_order': 65,
    },
    'NOTIFICATION_MIN_SEVERITY': {
        'title': 'Notification Minimum Severity',
        'description': 'Suppress static notifications below this severity. Empty keeps current behavior.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'select',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '',
        'options': [{'label': 'Not set', 'value': ''}, {'label': 'info', 'value': 'info'}, {'label': 'warning', 'value': 'warning'}, {'label': 'error', 'value': 'error'}, {'label': 'critical', 'value': 'critical'}],
        'validation': {'enum': ['', 'info', 'warning', 'error', 'critical']},
        'display_order': 69,
    },
    'NOTIFICATION_QUIET_HOURS': {
        'title': 'Notification Quiet Hours',
        'description': 'Quiet window in HH:MM-HH:MM format. Supports overnight ranges. Empty disables quiet hours.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '',
        'options': [],
        'validation': {'pattern': '^([01]\\d|2[0-3]):[0-5]\\d-([01]\\d|2[0-3]):[0-5]\\d$'},
        'display_order': 67,
    },
    'NOTIFICATION_REPORT_CHANNELS': {
        'title': 'Report Notification Channels',
        'description': 'Comma-separated route for report notifications. Empty keeps all configured channels.',
        'category': 'notification',
        'data_type': 'array',
        'ui_control': 'textarea',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '',
        'options': [{'label': 'wechat', 'value': 'wechat'}],
        'validation': {'allowed_values': ['wechat'], 'delimiter': ','},
        'display_order': 62,
    },
    'NOTIFICATION_SYSTEM_ERROR_CHANNELS': {
        'title': 'System Error Notification Channels',
        'description': 'Comma-separated route reserved for system error notifications. Empty keeps all configured channels.',
        'category': 'notification',
        'data_type': 'array',
        'ui_control': 'textarea',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '',
        'options': [{'label': 'wechat', 'value': 'wechat'}],
        'validation': {'allowed_values': ['wechat'], 'delimiter': ','},
        'display_order': 64,
    },
    'NOTIFICATION_TIMEZONE': {
        'title': 'Notification Timezone',
        'description': 'IANA timezone for quiet hours, e.g. Asia/Shanghai. Empty follows TZ or the local system timezone.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '',
        'options': [],
        'validation': {'timezone': True},
        'display_order': 68,
    },
    'NTFY_TOKEN': {
        'title': 'ntfy Token',
        'description': 'Optional ntfy bearer token for protected topics or self-hosted servers.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 45,
    },
    'NTFY_URL': {
        'title': 'ntfy URL',
        'description': 'Full ntfy publish endpoint including topic path, e.g. https://ntfy.sh/my-topic.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {'item_type': 'url', 'allowed_schemes': ['http', 'https']},
        'display_order': 44,
    },
    'PUSHOVER_API_TOKEN': {
        'title': 'Pushover API Token',
        'description': 'Pushover application API token.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 43,
    },
    'PUSHOVER_USER_KEY': {
        'title': 'Pushover User Key',
        'description': 'Pushover user key (from https://pushover.net).',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 42,
    },
    'PUSHPLUS_TOKEN': {
        'title': 'PushPlus Token',
        'description': 'Token for PushPlus notifications.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 40,
    },
    'PUSHPLUS_TOPIC': {
        'title': 'PushPlus Topic',
        'description': 'PushPlus group topic code for one-to-many push.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 41,
    },
    'REPORT_HISTORY_COMPARE_N': {
        'title': 'Report History Compare N',
        'description': 'Show last N analyses signal comparison per stock (0 = disabled).',
        'category': 'notification',
        'data_type': 'integer',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '0',
        'options': [],
        'validation': {'min': 0, 'max': 10},
        'display_order': 60,
    },
    'REPORT_INTEGRITY_ENABLED': {
        'title': 'Report Integrity Enabled',
        'description': 'Validate mandatory report fields after LLM output; retry or placeholder on missing.',
        'category': 'notification',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'true',
        'options': [],
        'validation': {},
        'display_order': 58,
    },
    'REPORT_INTEGRITY_RETRY': {
        'title': 'Report Integrity Retry',
        'description': 'Retry count when mandatory fields missing (0 = placeholder only, no retry).',
        'category': 'notification',
        'data_type': 'integer',
        'ui_control': 'number',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': '1',
        'options': [],
        'validation': {'min': 0, 'max': 3},
        'display_order': 59,
    },
    'REPORT_LANGUAGE': {
        'title': 'Report Language',
        'description': 'Default output language for reports and notification templates. Supported values: zh, en.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'select',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'zh',
        'options': [{'label': 'Chinese', 'value': 'zh'}, {'label': 'English', 'value': 'en'}],
        'validation': {'enum': ['zh', 'en']},
        'display_order': 56,
        'help_key': 'settings.notification.report_output',
        'examples': ['REPORT_LANGUAGE=zh', 'REPORT_LANGUAGE=en'],
        'docs': [{'label': '完整指南：环境变量完整列表', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表'}],
        'warning_codes': [],
    },
    'REPORT_RENDERER_ENABLED': {
        'title': 'Report Renderer Enabled',
        'description': 'Enable Jinja2 template rendering for reports. Default false for zero regression.',
        'category': 'notification',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'false',
        'options': [],
        'validation': {},
        'display_order': 58,
    },
    'REPORT_SHOW_LLM_MODEL': {
        'title': 'Show LLM Model in Reports',
        'description': 'Show the LLM model name in notification report footers. Disable to hide runtime model metadata. This option only affects report rendering and does not change runtime provider/model/Base URL/LiteLLM routing, migration, persistence, or cleanup behavior.',
        'category': 'notification',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'true',
        'options': [],
        'validation': {},
        'display_order': 54,
    },
    'REPORT_SUMMARY_ONLY': {
        'title': 'Report Summary Only',
        'description': 'Push only analysis summary without per-stock details. Suitable for quick overview when tracking many stocks (Issue #262).',
        'category': 'notification',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'false',
        'options': [],
        'validation': {},
        'display_order': 53,
    },
    'REPORT_TEMPLATES_DIR': {
        'title': 'Report Templates Dir',
        'description': 'Directory for Jinja2 report templates (relative to project root).',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'templates',
        'options': [],
        'validation': {},
        'display_order': 57,
    },
    'REPORT_TYPE': {
        'title': 'Report Type',
        'description': "Report format: 'simple' (concise), 'full' (detailed), or 'brief' (3-5 sentences).",
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'select',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'simple',
        'options': ['simple', 'full', 'brief'],
        'validation': {'enum': ['simple', 'full', 'brief']},
        'display_order': 55,
        'help_key': 'settings.notification.report_output',
        'examples': ['REPORT_TYPE=simple', 'REPORT_TYPE=full', 'REPORT_LANGUAGE=zh'],
        'docs': [{'label': '完整指南：环境变量完整列表', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#环境变量完整列表'}],
        'warning_codes': [],
    },
    'SERVERCHAN3_SENDKEY': {
        'title': 'ServerChan3 SendKey',
        'description': 'Server酱3 SendKey for push notifications.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 46,
    },
    'SINGLE_STOCK_NOTIFY': {
        'title': 'Single Stock Notify',
        'description': 'Push immediately after each single stock analysis instead of batching all results together.',
        'category': 'notification',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'false',
        'options': [],
        'validation': {},
        'display_order': 54,
    },
    'SLACK_BOT_TOKEN': {
        'title': 'Slack Bot Token',
        'description': 'Slack Bot Token (xoxb-...). Recommended; supports image upload. Takes priority over Webhook when both are configured.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 37,
        'help_key': 'settings.notification.chat_bots',
        'examples': ['SLACK_BOT_TOKEN=xoxb-xxxx', 'SLACK_CHANNEL_ID=C0123456789'],
        'docs': [{'label': '完整指南：通知渠道配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置'}],
        'warning_codes': ['secret_value'],
    },
    'SLACK_CHANNEL_ID': {
        'title': 'Slack Channel ID',
        'description': 'Slack channel ID (required when using Bot Token).',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 38,
    },
    'SLACK_WEBHOOK_URL': {
        'title': 'Slack Incoming Webhook URL',
        'description': 'Slack Incoming Webhook URL (text only, no image support).',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 39,
    },
    'TELEGRAM_BOT_TOKEN': {
        'title': 'Telegram Bot Token',
        'description': 'Telegram bot token (from @BotFather).',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 17,
        'help_key': 'settings.notification.telegram',
        'examples': ['TELEGRAM_BOT_TOKEN=123456:ABC-DEF', 'TELEGRAM_CHAT_ID=-1001234567890'],
        'docs': [{'label': '完整指南：Telegram', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#telegram'}],
        'warning_codes': ['secret_value'],
    },
    'TELEGRAM_CHAT_ID': {
        'title': 'Telegram Chat ID',
        'description': 'Telegram chat/group ID to send messages to.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 18,
        'help_key': 'settings.notification.telegram',
        'examples': ['TELEGRAM_CHAT_ID=-1001234567890', 'TELEGRAM_MESSAGE_THREAD_ID=123'],
        'docs': [{'label': '完整指南：Telegram', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#telegram'}],
        'warning_codes': [],
    },
    'TELEGRAM_MESSAGE_THREAD_ID': {
        'title': 'Telegram Thread ID',
        'description': 'Telegram topic/thread ID for group messages (optional).',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'text',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 19,
    },
    'WEBHOOK_VERIFY_SSL': {
        'title': 'Webhook SSL Verify',
        'description': 'Verify HTTPS certificates for webhook requests. Set to false ONLY for self-signed certs in trusted internal networks. WARNING: Disabling allows MITM attacks—do NOT use on public networks.',
        'category': 'notification',
        'data_type': 'boolean',
        'ui_control': 'switch',
        'is_sensitive': False,
        'is_required': False,
        'is_editable': True,
        'default_value': 'true',
        'options': [],
        'validation': {},
        'display_order': 53,
        'help_key': 'settings.notification.WEBHOOK_VERIFY_SSL',
        'examples': ['WEBHOOK_VERIFY_SSL=true', 'WEBHOOK_VERIFY_SSL=false'],
        'docs': [{'label': '完整指南：自定义 Webhook', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#自定义-webhook'}],
        'warning_codes': ['disabling_ssl_verify_is_risky'],
    },
    'WECHAT_WEBHOOK_URL': {
        'title': 'WeChat Webhook URL',
        'description': 'Webhook URL for enterprise WeChat bot.',
        'category': 'notification',
        'data_type': 'string',
        'ui_control': 'password',
        'is_sensitive': True,
        'is_required': False,
        'is_editable': True,
        'default_value': None,
        'options': [],
        'validation': {},
        'display_order': 10,
        'help_key': 'settings.notification.webhooks',
        'examples': ['WECHAT_WEBHOOK_URL=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxx'],
        'docs': [{'label': '完整指南：通知渠道配置', 'href': 'https://github.com/ZhuLinsen/daily_stock_analysis/blob/main/docs/full-guide.md#通知渠道详细配置'}],
        'warning_codes': ['webhook_secret_value'],
    },
}

