"""Independent market data schema

Revision: 0001
Revises:
"""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bond_yield_daily",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country", sa.String(length=5), nullable=False),
        sa.Column("term", sa.String(length=5), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("yield_value", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "country", "term", "date", name="uix_bond_country_term_date"
        ),
    )
    op.create_index(
        "ix_bond_country_term_date",
        "bond_yield_daily",
        ["country", "term", "date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bond_yield_daily_country"),
        "bond_yield_daily",
        ["country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bond_yield_daily_date"), "bond_yield_daily", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_bond_yield_daily_term"), "bond_yield_daily", ["term"], unique=False
    )
    op.create_table(
        "kline_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kline_snapshot_code"), "kline_snapshot", ["code"], unique=True
    )
    op.create_table(
        "macro_index_daily",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("index_code", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("pct_chg", sa.Float(), nullable=True),
        sa.Column("change_amount", sa.Float(), nullable=True),
        sa.Column("data_source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("index_code", "date", name="uix_macro_index_date"),
    )
    op.create_index(
        op.f("ix_macro_index_daily_date"), "macro_index_daily", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_macro_index_daily_index_code"),
        "macro_index_daily",
        ["index_code"],
        unique=False,
    )
    op.create_index(
        "ix_macro_index_date", "macro_index_daily", ["index_code", "date"], unique=False
    )
    op.create_table(
        "macro_indicator",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("indicator", sa.String(length=20), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("yoy", sa.Float(), nullable=True),
        sa.Column("mom", sa.Float(), nullable=True),
        sa.Column("extra_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("indicator", "period", name="uix_macro_indicator_period"),
    )
    op.create_index(
        op.f("ix_macro_indicator_indicator"),
        "macro_indicator",
        ["indicator"],
        unique=False,
    )
    op.create_index(
        "ix_macro_indicator_indicator_period",
        "macro_indicator",
        ["indicator", "period"],
        unique=False,
    )
    op.create_index(
        op.f("ix_macro_indicator_period"), "macro_indicator", ["period"], unique=False
    )
    op.create_table(
        "md_data_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset", sa.String(length=40), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("data_time", sa.String(length=64), nullable=True),
        sa.Column("checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=True),
        sa.Column("version", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset", "symbol"),
    )
    op.create_index(
        op.f("ix_md_data_state_dataset"), "md_data_state", ["dataset"], unique=False
    )
    op.create_index(
        op.f("ix_md_data_state_symbol"), "md_data_state", ["symbol"], unique=False
    )
    op.create_table(
        "md_dataset_policy",
        sa.Column("dataset", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("max_age_seconds", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("dataset"),
    )
    op.create_index(
        op.f("ix_md_dataset_policy_next_run_at"),
        "md_dataset_policy",
        ["next_run_at"],
        unique=False,
    )
    op.create_table(
        "md_import_issue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("raw_value", sa.String(length=500), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("table_name", "symbol", "field"),
    )
    op.create_table(
        "md_observation",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("dataset", sa.String(length=40), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("data_time", sa.String(length=64), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_md_observation_dataset"), "md_observation", ["dataset"], unique=False
    )
    op.create_index(
        op.f("ix_md_observation_fetched_at"),
        "md_observation",
        ["fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_md_observation_operation"),
        "md_observation",
        ["operation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_md_observation_request_key"),
        "md_observation",
        ["request_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_md_observation_symbol"), "md_observation", ["symbol"], unique=False
    )
    op.create_table(
        "md_service_heartbeat",
        sa.Column("component", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("detail", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("component"),
    )
    op.create_table(
        "md_source_subscription",
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("dataset", sa.String(length=40), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(), nullable=False),
        sa.Column("last_requested_at", sa.DateTime(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("request_key"),
    )
    op.create_index(
        op.f("ix_md_source_subscription_dataset"),
        "md_source_subscription",
        ["dataset"],
        unique=False,
    )
    op.create_index(
        op.f("ix_md_source_subscription_next_run_at"),
        "md_source_subscription",
        ["next_run_at"],
        unique=False,
    )
    op.create_table(
        "md_sync_job",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset", sa.String(length=40), nullable=False),
        sa.Column("active_key", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("trigger", sa.String(length=24), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("symbols", sa.JSON(), nullable=False),
        sa.Column("retry_of", sa.String(length=36), nullable=True),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("succeeded", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("active_key"),
    )
    op.create_index(
        op.f("ix_md_sync_job_created_at"), "md_sync_job", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_md_sync_job_dataset"), "md_sync_job", ["dataset"], unique=False
    )
    op.create_index(
        op.f("ix_md_sync_job_lease_until"), "md_sync_job", ["lease_until"], unique=False
    )
    op.create_index(
        op.f("ix_md_sync_job_status"), "md_sync_job", ["status"], unique=False
    )
    op.create_table(
        "md_trading_day",
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("day"),
    )
    op.create_table(
        "news_intel",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query_id", sa.String(length=64), nullable=True),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("dimension", sa.String(length=32), nullable=True),
        sa.Column("query", sa.String(length=255), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("published_date", sa.DateTime(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.Column("query_source", sa.String(length=32), nullable=True),
        sa.Column("requester_platform", sa.String(length=20), nullable=True),
        sa.Column("requester_user_id", sa.String(length=64), nullable=True),
        sa.Column("requester_user_name", sa.String(length=64), nullable=True),
        sa.Column("requester_chat_id", sa.String(length=64), nullable=True),
        sa.Column("requester_message_id", sa.String(length=64), nullable=True),
        sa.Column("requester_query", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", name="uix_news_url"),
    )
    op.create_index(
        "ix_news_code_pub", "news_intel", ["code", "published_date"], unique=False
    )
    op.create_index(op.f("ix_news_intel_code"), "news_intel", ["code"], unique=False)
    op.create_index(
        op.f("ix_news_intel_dimension"), "news_intel", ["dimension"], unique=False
    )
    op.create_index(
        op.f("ix_news_intel_fetched_at"), "news_intel", ["fetched_at"], unique=False
    )
    op.create_index(
        op.f("ix_news_intel_provider"), "news_intel", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_news_intel_published_date"),
        "news_intel",
        ["published_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_intel_query_id"), "news_intel", ["query_id"], unique=False
    )
    op.create_index(
        op.f("ix_news_intel_query_source"), "news_intel", ["query_source"], unique=False
    )
    op.create_table(
        "quote_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quote_snapshot_code"), "quote_snapshot", ["code"], unique=True
    )
    op.create_table(
        "rss_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rss_cache_cache_key"), "rss_cache", ["cache_key"], unique=True
    )
    op.create_table(
        "stock_daily",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("pct_chg", sa.Float(), nullable=True),
        sa.Column("ma5", sa.Float(), nullable=True),
        sa.Column("ma10", sa.Float(), nullable=True),
        sa.Column("ma20", sa.Float(), nullable=True),
        sa.Column("volume_ratio", sa.Float(), nullable=True),
        sa.Column("data_source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "date", name="uix_code_date"),
    )
    op.create_index("ix_code_date", "stock_daily", ["code", "date"], unique=False)
    op.create_index(op.f("ix_stock_daily_code"), "stock_daily", ["code"], unique=False)
    op.create_index(op.f("ix_stock_daily_date"), "stock_daily", ["date"], unique=False)
    op.create_table(
        "stock_meta",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("ipo_date", sa.Date(), nullable=True),
        sa.Column("revenue_latest", sa.Float(), nullable=True),
        sa.Column("net_profit_latest", sa.Float(), nullable=True),
        sa.Column("operating_cf_latest", sa.Float(), nullable=True),
        sa.Column("revenue_ttm", sa.Float(), nullable=True),
        sa.Column("parent_net_profit_ttm", sa.Float(), nullable=True),
        sa.Column("deducted_net_profit_ttm", sa.Float(), nullable=True),
        sa.Column("debt_ratio", sa.Float(), nullable=True),
        sa.Column("financial_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("report_date", sa.String(length=20), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_meta_code"), "stock_meta", ["code"], unique=True)
    op.create_index(
        op.f("ix_stock_meta_market"), "stock_meta", ["market"], unique=False
    )
    op.create_index(
        "ix_stock_meta_market_status", "stock_meta", ["market", "status"], unique=False
    )
    op.create_index("ix_stock_meta_name", "stock_meta", ["name"], unique=False)
    op.create_index(
        op.f("ix_stock_meta_status"), "stock_meta", ["status"], unique=False
    )
    op.create_table(
        "tool_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tool_cache_cache_key"), "tool_cache", ["cache_key"], unique=True
    )
    op.create_table(
        "md_sync_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["md_sync_job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "symbol"),
    )
    op.create_index(
        op.f("ix_md_sync_item_job_id"), "md_sync_item", ["job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_md_sync_item_job_id"), table_name="md_sync_item")
    op.drop_table("md_sync_item")
    op.drop_index(op.f("ix_tool_cache_cache_key"), table_name="tool_cache")
    op.drop_table("tool_cache")
    op.drop_index(op.f("ix_stock_meta_status"), table_name="stock_meta")
    op.drop_index("ix_stock_meta_name", table_name="stock_meta")
    op.drop_index("ix_stock_meta_market_status", table_name="stock_meta")
    op.drop_index(op.f("ix_stock_meta_market"), table_name="stock_meta")
    op.drop_index(op.f("ix_stock_meta_code"), table_name="stock_meta")
    op.drop_table("stock_meta")
    op.drop_index(op.f("ix_stock_daily_date"), table_name="stock_daily")
    op.drop_index(op.f("ix_stock_daily_code"), table_name="stock_daily")
    op.drop_index("ix_code_date", table_name="stock_daily")
    op.drop_table("stock_daily")
    op.drop_index(op.f("ix_rss_cache_cache_key"), table_name="rss_cache")
    op.drop_table("rss_cache")
    op.drop_index(op.f("ix_quote_snapshot_code"), table_name="quote_snapshot")
    op.drop_table("quote_snapshot")
    op.drop_index(op.f("ix_news_intel_query_source"), table_name="news_intel")
    op.drop_index(op.f("ix_news_intel_query_id"), table_name="news_intel")
    op.drop_index(op.f("ix_news_intel_published_date"), table_name="news_intel")
    op.drop_index(op.f("ix_news_intel_provider"), table_name="news_intel")
    op.drop_index(op.f("ix_news_intel_fetched_at"), table_name="news_intel")
    op.drop_index(op.f("ix_news_intel_dimension"), table_name="news_intel")
    op.drop_index(op.f("ix_news_intel_code"), table_name="news_intel")
    op.drop_index("ix_news_code_pub", table_name="news_intel")
    op.drop_table("news_intel")
    op.drop_table("md_trading_day")
    op.drop_index(op.f("ix_md_sync_job_status"), table_name="md_sync_job")
    op.drop_index(op.f("ix_md_sync_job_lease_until"), table_name="md_sync_job")
    op.drop_index(op.f("ix_md_sync_job_dataset"), table_name="md_sync_job")
    op.drop_index(op.f("ix_md_sync_job_created_at"), table_name="md_sync_job")
    op.drop_table("md_sync_job")
    op.drop_index(
        op.f("ix_md_source_subscription_next_run_at"),
        table_name="md_source_subscription",
    )
    op.drop_index(
        op.f("ix_md_source_subscription_dataset"), table_name="md_source_subscription"
    )
    op.drop_table("md_source_subscription")
    op.drop_table("md_service_heartbeat")
    op.drop_index(op.f("ix_md_observation_symbol"), table_name="md_observation")
    op.drop_index(op.f("ix_md_observation_request_key"), table_name="md_observation")
    op.drop_index(op.f("ix_md_observation_operation"), table_name="md_observation")
    op.drop_index(op.f("ix_md_observation_fetched_at"), table_name="md_observation")
    op.drop_index(op.f("ix_md_observation_dataset"), table_name="md_observation")
    op.drop_table("md_observation")
    op.drop_table("md_import_issue")
    op.drop_index(
        op.f("ix_md_dataset_policy_next_run_at"), table_name="md_dataset_policy"
    )
    op.drop_table("md_dataset_policy")
    op.drop_index(op.f("ix_md_data_state_symbol"), table_name="md_data_state")
    op.drop_index(op.f("ix_md_data_state_dataset"), table_name="md_data_state")
    op.drop_table("md_data_state")
    op.drop_index(op.f("ix_macro_indicator_period"), table_name="macro_indicator")
    op.drop_index("ix_macro_indicator_indicator_period", table_name="macro_indicator")
    op.drop_index(op.f("ix_macro_indicator_indicator"), table_name="macro_indicator")
    op.drop_table("macro_indicator")
    op.drop_index("ix_macro_index_date", table_name="macro_index_daily")
    op.drop_index(
        op.f("ix_macro_index_daily_index_code"), table_name="macro_index_daily"
    )
    op.drop_index(op.f("ix_macro_index_daily_date"), table_name="macro_index_daily")
    op.drop_table("macro_index_daily")
    op.drop_index(op.f("ix_kline_snapshot_code"), table_name="kline_snapshot")
    op.drop_table("kline_snapshot")
    op.drop_index(op.f("ix_bond_yield_daily_term"), table_name="bond_yield_daily")
    op.drop_index(op.f("ix_bond_yield_daily_date"), table_name="bond_yield_daily")
    op.drop_index(op.f("ix_bond_yield_daily_country"), table_name="bond_yield_daily")
    op.drop_index("ix_bond_country_term_date", table_name="bond_yield_daily")
    op.drop_table("bond_yield_daily")
    # ### end Alembic commands ###
