import { describe, expect, it } from 'vitest';
import {
  assistantEvidenceIdFromHref,
  assistantEvidenceIndexFromTrace,
  assistantEvidenceReferenceForId,
  replaceAssistantEvidenceMarkers,
} from './assistantEvidence';

describe('assistant evidence presentation adapter', () => {
  it('joins compact evidence records with the existing projected tool result', () => {
    const index = assistantEvidenceIndexFromTrace({
      evidence: [{
        evidence_id: 'ev_market',
        action_id: 'action-market',
        data_time: '2026-09-03 13:07',
        source_refs: ['tool:read_market_indices'],
      }],
      tool_results: [{
        action_id: 'action-market',
        tool_name: 'read_market_indices',
        source_labels: ['新浪财经'],
        result_summary: '指数行情已返回。',
        result_items: [{
          title: '上证指数',
          source: '新浪财经',
          published_at: '13:07',
          summary: '3942 点，涨幅 +0.02%。',
          attributes: [{ name: 'price', value: '3942.0879' }],
        }],
      }],
    });

    expect(index.get('ev_market')).toEqual(expect.objectContaining({
      evidenceId: 'ev_market',
      actionId: 'action-market',
      toolName: 'read_market_indices',
      dataTime: '2026-09-03 13:07',
      sourceLabels: ['新浪财经'],
      resultSummary: '指数行情已返回。',
      resultItems: [expect.objectContaining({
        title: '上证指数',
        publishedAt: '13:07',
        attributes: [{ name: 'price', value: '3942.0879' }],
      })],
    }));
  });

  it('keeps PDF citation details scoped to the exact retrieved chunk', () => {
    const index = assistantEvidenceIndexFromTrace({
      evidence: [{
        evidence_id: 'ev_search_action',
        action_id: 'action-pdf-search',
        tool_name: 'search_knowledge_base',
        success: true,
      }],
      tool_results: [{
        action_id: 'action-pdf-search',
        tool_name: 'search_knowledge_base',
        success: true,
        result_items: [
          {
            id: 'kb_level-zero',
            evidence_id: 'ev_kb_level-zero',
            title: 'Agentic_Design_Patterns_Complete.pdf · 第 14 页',
            url: '/api/v1/knowledge-bases/documents/doc-1/content#page=14',
            summary: 'Level 0 is without tools, memory, or environment interaction.',
          },
          {
            id: 'kb_unrelated',
            evidence_id: 'ev_kb_unrelated',
            title: 'Agentic_Design_Patterns_Complete.pdf · 第 85 页',
            url: '/api/v1/knowledge-bases/documents/doc-1/content#page=85',
            summary: 'An unrelated code example.',
          },
        ],
      }],
      claim_evidence: [{
        evidence_ids: ['ev_kb_level-zero'],
        evidence: [{
          evidence_id: 'ev_kb_level-zero',
          action_id: 'action-pdf-search',
          tool_name: 'search_knowledge_base',
          source_refs: ['/api/v1/knowledge-bases/documents/doc-1/content#page=14'],
        }],
      }],
    });

    expect(assistantEvidenceReferenceForId(index, 'ev_kb_level-zero')).toEqual(
      expect.objectContaining({
        evidenceId: 'ev_kb_level-zero',
        sourceRefs: ['/api/v1/knowledge-bases/documents/doc-1/content#page=14'],
        resultItems: [expect.objectContaining({
          title: 'Agentic_Design_Patterns_Complete.pdf · 第 14 页',
          summary: 'Level 0 is without tools, memory, or environment interaction.',
        })],
      }),
    );
    expect(assistantEvidenceReferenceForId(index, 'ev_kb_level-zero')?.resultItems).toHaveLength(1);
  });

  it('uses one stable circled footnote for repeated evidence markers', () => {
    expect(replaceAssistantEvidenceMarkers(
      '第一处【证据 ev_a】；再次引用【证据：ev_a】；裸标记【ev_a】；第二条【ev_b】。',
    )).toBe(
      '第一处[①](#assistant-evidence-ev_a)；再次引用[①](#assistant-evidence-ev_a)；裸标记[①](#assistant-evidence-ev_a)；第二条[②](#assistant-evidence-ev_b)。',
    );
  });

  it('parses only citations generated by the presentation adapter', () => {
    expect(assistantEvidenceIdFromHref('#assistant-evidence-ev_a')).toBe('ev_a');
    expect(assistantEvidenceIdFromHref('#assistant-evidence-market%3A0')).toBe('market:0');
    expect(assistantEvidenceIdFromHref('https://example.com/evidence')).toBeNull();
  });

  it('resolves a shortened model evidence ID when the prefix is unique', () => {
    const index = assistantEvidenceIndexFromTrace({
      evidence: [{
        evidence_id: 'ev_market0123456789',
        action_id: 'market-1',
      }],
    });

    expect(assistantEvidenceReferenceForId(index, 'ev_market')).toEqual(
      expect.objectContaining({ evidenceId: 'ev_market0123456789' }),
    );
  });

  it('does not let a shortened claim ID shadow its canonical evidence details', () => {
    const index = assistantEvidenceIndexFromTrace({
      evidence: [{
        evidence_id: 'ev_market0123456789',
        action_id: 'market-1',
      }],
      claim_evidence: [{
        evidence_ids: ['ev_market'],
      }],
      tool_results: [{
        action_id: 'market-1',
        result_summary: '指数行情已返回。',
      }],
    });

    expect(assistantEvidenceReferenceForId(index, 'ev_market')).toEqual(
      expect.objectContaining({
        evidenceId: 'ev_market0123456789',
        resultSummary: '指数行情已返回。',
      }),
    );
  });

  it('does not turn an explicitly ineligible or unknown ID into a citation target', () => {
    const index = assistantEvidenceIndexFromTrace({
      evidence: [{
        evidence_id: 'ev_empty',
        success: true,
        has_data: false,
        evidence_eligible: false,
      }],
      tool_results: [{
        action_id: 'empty-call',
        evidence_id: 'ev_empty',
        success: true,
        has_data: false,
        evidence_eligible: false,
      }],
      claim_evidence: [{ evidence_ids: ['ev_missing'] }],
    });

    expect(index.has('ev_empty')).toBe(false);
    expect(index.has('ev_missing')).toBe(false);
    expect(assistantEvidenceReferenceForId(index, 'ev_empty')).toBeUndefined();
    expect(assistantEvidenceReferenceForId(index, 'ev_missing')).toBeUndefined();
  });

  it('keeps unresolved streaming markers non-clickable without leaking internal IDs', () => {
    const index = assistantEvidenceIndexFromTrace({
      evidence: [{
        evidence_id: 'ev_ready0123456789',
        success: true,
        has_data: true,
        evidence_eligible: true,
      }],
    });

    expect(replaceAssistantEvidenceMarkers(
      '已核验【证据 ev_ready】；未知【证据 ev_missing】。',
      index,
    )).toBe(
      '已核验[①](#assistant-evidence-ev_ready0123456789)；未知。（部分证据暂未关联）',
    );
  });
});
