/** 工具名 → 中文标签。供 GenericToolDrawer 等展示用。 */
export const TOOL_LABELS: Record<string, string> = {
  search_stocks: '股票搜索',
  manage_watchlist: '自选股管理',
  get_data_health: '数据维护状态',
  get_multi_stock_snapshot: '多股数据快照',
  get_multi_stock_financials: '多股财务快照',
  get_multi_stock_decision_evidence: '多股深度研究证据',
  evaluate_market_mainline_gate: '批次共享市场主线判断',
  evaluate_multi_stock_buy_criteria: '资深分析师八维买入分析',
  analyze_stock_catalysts: '公司催化事件核验',
  get_domain_stock_candidates: '领域股票候选池',
  get_company_theme_evidence: '单股主题业务证据',
  get_domain_board_catalog: '实时概念板块目录',
  screen_atr_volatility_stocks: '全市场 ATR 量化筛选',
  get_realtime_quotes: '实时行情',
  get_kline: 'K线数据',
  get_history_data: '历史行情',
  get_technical_indicators: '技术指标',
  get_market_status: '大盘状态',
  prepare_market_mainline_snapshot: '市场主线快照',
  get_sector_list: '板块列表',
  get_stock_info: '股票信息',
  get_financials: '财务摘要',
  get_balance_sheet: '资产负债表',
  get_income_statement: '利润表',
  get_cashflow: '现金流量表',
  get_valuation_ratios: '估值指标',
  get_shareholder_structure: '股东结构',
  get_business_segments: '主营构成',
  get_consensus_estimates: '一致预期',
  get_peer_comparison: '同行比较',
  search_news: '新闻搜索',
  search_financial_news: '财经资讯',
  list_financial_sources: '股市资讯源',
  inspect_financial_source: '资讯源详情',
  read_financial_feed: '指定资讯源',
  read_financial_article: '资讯全文',
  discover_rss_sources: 'RSSHub 财经来源',
  inspect_rss_source: 'RSSHub 来源详情',
  read_rss_feed: '读取 RSS Feed',
  read_rss_item: '读取 RSS 条目与文档',
  read_text_document: '读取原始文本文件',
  transform_webpage_to_feed: '网页转资讯流',
  export_financial_feed: '资讯订阅下载',
  export_rss_feed: 'RSS 纯文本订阅下载',
  get_risk_events: '风险事件',
  get_announcements: '公告查询',
  get_research_report: '研报查询',
  get_social_sentiment: '社交舆情',
  get_index_data: '指数行情',
  get_bond_yield: '债券收益率',
  get_macro_indicator: '宏观指标',
  get_sector_flow: '板块资金流',
  get_stock_capital_flow: '个股资金流',
  get_market_breadth: '市场宽度',
  websearch: '网络搜索',
  webfetch: '网页抓取',
};
