/** 工具名 → 中文标签。供 GenericToolDrawer 等展示用。 */
export const TOOL_LABELS: Record<string, string> = {
  search_stocks: '股票搜索',
  manage_watchlist: '自选股管理',
  get_data_health: '数据维护状态',
  get_multi_stock_snapshot: '多股决策快照',
  get_multi_stock_decision_evidence: '专业买入决策证据',
  get_theme_stock_candidates: '主题股票候选池',
  screen_atr_volatility_stocks: '全市场 ATR 量化筛选',
  get_realtime_quotes: '实时行情',
  get_kline: 'K线数据',
  get_history_data: '历史行情',
  get_technical_indicators: '技术指标',
  get_market_status: '大盘状态',
  get_sector_list: '板块列表',
  get_stock_info: '股票信息',
  get_financials: '财务摘要',
  get_balance_sheet: '资产负债表',
  get_income_statement: '利润表',
  get_cashflow: '现金流量表',
  get_valuation_ratios: '估值指标',
  get_shareholder_structure: '股东结构',
  get_business_segments: '主营构成',
  get_consensus_estimates: '一致预期',
  get_peer_comparison: '同行比较',
  search_news: '新闻搜索',
  search_financial_news: '财经资讯',
  list_financial_sources: '股市资讯源',
  inspect_financial_source: '资讯源详情',
  read_financial_feed: '指定资讯源',
  read_financial_article: '资讯全文',
  transform_webpage_to_feed: '网页转资讯流',
  export_financial_feed: '资讯订阅下载',
  get_risk_events: '风险事件',
  get_announcements: '公告查询',
  get_research_report: '研报查询',
  get_social_sentiment: '社交舆情',
  get_index_data: '指数行情',
  get_bond_yield: '债券收益率',
  get_macro_indicator: '宏观指标',
  get_sector_flow: '板块资金流',
  get_stock_capital_flow: '个股资金流',
  get_market_breadth: '市场宽度',
  websearch: '网络搜索',
  webfetch: '网页抓取',
};
