/** 工具名 → 中文标签。供 GenericToolDrawer 等展示用。 */
export const TOOL_LABELS: Record<string, string> = {
  get_realtime_quotes: '实时行情',
  get_kline: 'K线数据',
  get_history_data: '历史行情',
  get_market_status: '大盘状态',
  get_sector_list: '板块列表',
  get_stock_info: '股票信息',
  get_financials: '财务摘要',
  get_balance_sheet: '资产负债表',
  get_income_statement: '利润表',
  get_cashflow: '现金流量表',
  get_valuation_ratios: '估值指标',
  get_price_overdraft_signal: '股价透支判定',
  get_shareholder_structure: '股东结构',
  search_news: '新闻搜索',
  get_risk_events: '风险事件',
  get_sentiment: '舆情数据',
  get_announcements: '公告查询',
  get_research_report: '研报查询',
  get_social_sentiment: '社交舆情',
  get_index_data: '指数行情',
  get_bond_yield: '债券收益率',
  get_macro_indicator: '宏观指标',
  get_sector_flow: '板块资金流',
  get_market_breadth: '市场宽度',
  websearch: '网络搜索',
  webfetch: '网页抓取',
  list_rss_sources: 'RSS源目录',
  read_rss_feed: 'RSS资讯',
  read_rss_item: 'RSS全文',
};
