"""Runtime data initialization for the capability registry (part 1)."""

SOURCE = (
    'Compiler = Callable[\n'
    '    [\n'
    '        str,\n'
    '        str,\n'
    '        BaseModel,\n'
    '        tuple[InputReferenceV2, ...],\n'
    '        ResultSelectionV2 | None,\n'
    '        int,\n'
    '    ],\n'
    '    NormalizedIntent[Any],\n'
    ']\n'
    '_SUPPORTED_PERIODS: Mapping[str, frozenset[str]] = MappingProxyType(\n'
    '    {\n'
    '        "debt_ratio": frozenset({"latest_report", "previous_fiscal_year", "fiscal_year"}),\n'
    '        "revenue": frozenset({"ttm", "previous_fiscal_year", "fiscal_year"}),\n'
    '        "net_profit": frozenset({"previous_fiscal_year", "fiscal_year"}),\n'
    '        "deducted_net_profit": frozenset({"ttm", "previous_fiscal_year", "fiscal_year"}),\n'
    '    }\n'
    ')\n'
    '_DEFAULT_PERIOD: Mapping[str, str] = MappingProxyType(\n'
    '    {\n'
    '        "debt_ratio": "latest_report",\n'
    '        "revenue": "previous_fiscal_year",\n'
    '        "net_profit": "previous_fiscal_year",\n'
    '        "deducted_net_profit": "previous_fiscal_year",\n'
    '    }\n'
    ')\n'
    '_INTENT_MODELS: Mapping[Capability, type[BaseModel]] = MappingProxyType(\n'
    '    {\n'
    '        Capability.GENERAL_RESPONSE: intent_models.GeneralResponseIntent,\n'
    '        Capability.SECURITY_LOOKUP: intent_models.SecurityLookupIntent,\n'
    '        Capability.REALTIME_QUOTE: intent_models.RealtimeQuoteIntent,\n'
    '        Capability.PRICE_HISTORY: intent_models.PriceHistoryIntent,\n'
    '        Capability.TECHNICAL_ANALYSIS: intent_models.TechnicalAnalysisIntent,\n'
    '        Capability.FUNDAMENTAL_ANALYSIS: intent_models.FundamentalAnalysisIntent,\n'
    '        Capability.VALUATION_ANALYSIS: intent_models.ValuationAnalysisIntent,\n'
    '        Capability.FINANCIAL_STATEMENT_ANALYSIS: intent_models.FinancialStatementAnalysisIntent,\n'
    '        Capability.NEWS_ANALYSIS: intent_models.NewsAnalysisIntent,\n'
    '        Capability.ANNOUNCEMENT_ANALYSIS: intent_models.AnnouncementAnalysisIntent,\n'
    '        Capability.RISK_ANALYSIS: intent_models.RiskAnalysisIntent,\n'
    '        Capability.REGULATORY_ANALYSIS: intent_models.RegulatoryAnalysisIntent,\n'
    '        Capability.RESEARCH_REPORT_ANALYSIS: intent_models.ResearchReportAnalysisIntent,\n'
    '        Capability.CATALYST_ANALYSIS: intent_models.CatalystAnalysisIntent,\n'
    '        Capability.SOCIAL_SENTIMENT_ANALYSIS: intent_models.SocialSentimentAnalysisIntent,\n'
    '        Capability.STOCK_COMPARISON: intent_models.StockComparisonIntent,\n'
    '        Capability.STOCK_DEEP_RESEARCH: intent_models.StockDeepResearchIntent,\n'
    '        Capability.INVESTMENT_DECISION: intent_models.InvestmentDecisionIntent,\n'
    '        Capability.MARKET_OVERVIEW: intent_models.MarketOverviewIntent,\n'
    '        Capability.MARKET_MAINLINE_RESEARCH: intent_models.MarketMainlineResearchIntent,\n'
    '        Capability.SECTOR_ANALYSIS: intent_models.SectorAnalysisIntent,\n'
    '        Capability.CAPITAL_FLOW_ANALYSIS: intent_models.CapitalFlowAnalysisIntent,\n'
    '        Capability.MACRO_ANALYSIS: intent_models.MacroAnalysisIntent,\n'
    '        Capability.INDUSTRY_RESEARCH: intent_models.IndustryResearchIntent,\n'
    '        Capability.THEME_STOCK_DISCOVERY: intent_models.ThemeStockDiscoveryIntent,\n'
    '        Capability.THEME_BUSINESS_EVIDENCE: intent_models.ThemeBusinessEvidenceIntent,\n'
    '        Capability.STOCK_SCREENING: intent_models.StockScreeningIntent,\n'
    '        Capability.COLLECTION_FINANCIAL_FILTER: intent_models.CollectionFinancialFilterIntent,\n'
    '        Capability.WATCHLIST_QUERY: intent_models.WatchlistQueryIntent,\n'
    '        Capability.WATCHLIST_MUTATION: intent_models.WatchlistMutationIntent,\n'
    '        Capability.WATCHLIST_GROUP_MANAGEMENT: intent_models.WatchlistGroupManagementIntent,\n'
    '        Capability.DATA_HEALTH: intent_models.DataHealthIntent,\n'
    '        Capability.FORMAL_ANALYSIS: intent_models.FormalAnalysisIntent,\n'
    '        Capability.ANALYSIS_HISTORY: intent_models.AnalysisHistoryIntent,\n'
    '        Capability.ANALYSIS_TEMPLATE_MANAGEMENT: intent_models.AnalysisTemplateManagementIntent,\n'
    '        Capability.BATCH_ANALYSIS: intent_models.BatchAnalysisIntent,\n'
    '        Capability.BATCH_RUN_MANAGEMENT: intent_models.BatchRunManagementIntent,\n'
    '        Capability.ANALYSIS_SCHEDULE_MANAGEMENT: intent_models.AnalysisScheduleManagementIntent,\n'
    '        Capability.NOTIFICATION: intent_models.NotificationIntent,\n'
    '        Capability.FINANCIAL_SOURCE_DISCOVERY: intent_models.FinancialSourceDiscoveryIntent,\n'
    '        Capability.FINANCIAL_FEED_READ: intent_models.FinancialFeedReadIntent,\n'
    '        Capability.FINANCIAL_ARTICLE_READ: intent_models.FinancialArticleReadIntent,\n'
    '        Capability.WEBPAGE_FEED_TRANSFORM: intent_models.WebpageFeedTransformIntent,\n'
    '        Capability.FINANCIAL_FEED_EXPORT: intent_models.FinancialFeedExportIntent,\n'
    '        Capability.PUBLIC_WEB_RESEARCH: intent_models.PublicWebResearchIntent,\n'
    '        Capability.TRADE_EXECUTION: intent_models.TradeExecutionIntent,\n'
    '    }\n'
    ')\n'
    '_COMPILERS: Mapping[Capability, Compiler] = MappingProxyType(\n'
    '    {\n'
    '        Capability.PRICE_HISTORY: _price_history_compiler,\n'
    '        Capability.TECHNICAL_ANALYSIS: _simple_compiler(\n'
    '            program_fields={"count": 120},\n'
    '        ),\n'
    '        Capability.FUNDAMENTAL_ANALYSIS: _simple_compiler(\n'
    '            aliases={"business_category": "category"},\n'
    '        ),\n'
    '        Capability.VALUATION_ANALYSIS: _simple_compiler(\n'
    '            aliases={\n'
    '                "include_history": "with_history",\n'
    '                "consensus_metric": "metric",\n'
    '                "peer_dimension": "dimension",\n'
    '            }\n'
    '        ),\n'
    '        Capability.NEWS_ANALYSIS: _simple_compiler(\n'
    '            program_fields={\n'
    '                "use_cache": True,\n'
    '                "include_content": True,\n'
    '                "fallback_to_web": False,\n'
    '            },\n'
    '        ),\n'
    '        Capability.REGULATORY_ANALYSIS: _simple_compiler(\n'
    '            program_fields={"include_content": True, "fallback_to_web": False},\n'
    '        ),\n'
    '        Capability.SOCIAL_SENTIMENT_ANALYSIS: _simple_compiler(\n'
    '            program_fields={"max_pages": 5},\n'
    '        ),\n'
    '        Capability.MARKET_OVERVIEW: _simple_compiler(\n'
    '            defaults={\n'
    '                "include_index": (\n'
    '                    True,\n'
    '                    "用户未排除指数概览，按包含指数执行。",\n'
    '                ),\n'
    '            }\n'
    '        ),\n'
    '        Capability.SECTOR_ANALYSIS: _simple_compiler(\n'
    '            aliases={"sector_type": "type"},\n'
    '            defaults={\n'
    '                "sector_type": ("industry", "用户未指定板块类型，按行业板块执行。"),\n'
    '                "period": ("5d", "用户未指定资金周期，按 5 日执行。"),\n'
    '                "top_n": (10, "用户未指定板块数量，按前 10 个执行。"),\n'
    '            },\n'
    '            program_fields={"include_content": True},\n'
    '        ),\n'
    '        Capability.MACRO_ANALYSIS: _simple_compiler(\n'
    '            aliases={\n'
    '                "bond_yield": "include_bond_yield",\n'
    '                "monetary_operations": "include_monetary_operations",\n'
    '                "research_query": "query",\n'
    '                "research_subjects": "subjects",\n'
    '            },\n'
    '            program_fields={"include_content": True, "fallback_to_web": False},\n'
    '        ),\n'
    '        Capability.INDUSTRY_RESEARCH: _industry_compiler,\n'
    '        Capability.THEME_STOCK_DISCOVERY: _theme_compiler,\n'
    '        Capability.THEME_BUSINESS_EVIDENCE: _theme_evidence_compiler,\n'
    '        Capability.STOCK_SCREENING: _simple_compiler(\n'
    '            program_fields={"refresh_if_stale": True},\n'
    '        ),\n'
    '        Capability.COLLECTION_FINANCIAL_FILTER: _financial_filter_compiler,\n'
    '        Capability.INVESTMENT_DECISION: _investment_compiler,\n'
    '        Capability.WATCHLIST_QUERY: _simple_compiler(aliases={"themes": "domains"}),\n'
    '        Capability.FORMAL_ANALYSIS: _simple_compiler(aliases={"template_id": "prompt_template_id"}),\n'
    '        Capability.ANALYSIS_HISTORY: _simple_compiler(),\n'
    '        Capability.ANALYSIS_TEMPLATE_MANAGEMENT: _simple_compiler(),\n'
    '        Capability.BATCH_ANALYSIS: _simple_compiler(aliases={"template_id": "prompt_template_id"}),\n'
    '        Capability.BATCH_RUN_MANAGEMENT: _simple_compiler(),\n'
    '        Capability.ANALYSIS_SCHEDULE_MANAGEMENT: _simple_compiler(\n'
    '            aliases={"template_id": "prompt_template_id"},\n'
    '        ),\n'
    '        Capability.FINANCIAL_SOURCE_DISCOVERY: _simple_compiler(\n'
    '            program_fields={"force": False},\n'
    '        ),\n'
    '        Capability.FINANCIAL_FEED_READ: _feed_compiler,\n'
    '        Capability.FINANCIAL_FEED_EXPORT: _feed_compiler,\n'
    '        Capability.WEBPAGE_FEED_TRANSFORM: _webpage_compiler,\n'
    '        Capability.PUBLIC_WEB_RESEARCH: _simple_compiler(\n'
    '            program_fields={\n'
    '                "numResults": 10,\n'
    '                "livecrawl": "fallback",\n'
    '                "type": "auto",\n'
    '                "contextMaxCharacters": 30_000,\n'
    '                "includeContent": True,\n'
    '                "format": "markdown",\n'
    '            }\n'
    '        ),\n'
    '    }\n'
    ')\n'
    '_DETERMINISTIC_CONTRACTS = frozenset(\n'
    '    {\n'
    '        "industry_ranked_domains",\n'
    '        "theme_stock_discovery",\n'
    '        "theme_business_evidence",\n'
    '        "collection_financial_filter",\n'
    '        "stock_screening",\n'
    '        "investment_decision",\n'
    '    }\n'
    ')\n'
    '_PROGRAM_DEFAULT_FIELDS: Mapping[Capability, frozenset[str]] = MappingProxyType(\n'
    '    {\n'
    '        Capability.PRICE_HISTORY: frozenset({"period"}),\n'
    '        Capability.MARKET_OVERVIEW: frozenset({"include_index"}),\n'
    '        Capability.SECTOR_ANALYSIS: frozenset(\n'
    '            {\n'
    '                "sector_type",\n'
    '                "period",\n'
    '                "top_n",\n'
    '            }\n'
    '        ),\n'
    '        Capability.THEME_STOCK_DISCOVERY: frozenset({"output.*"}),\n'
    '        Capability.THEME_BUSINESS_EVIDENCE: frozenset({"days", "output.*"}),\n'
    '        Capability.COLLECTION_FINANCIAL_FILTER: frozenset(\n'
    '            {\n'
    '                "predicates.*.period",\n'
    '                "output.*",\n'
    '            }\n'
    '        ),\n'
    '        Capability.INVESTMENT_DECISION: frozenset(\n'
    '            {\n'
    '                "mainline_strategy",\n'
    '                "output.*",\n'
    '            }\n'
    '        ),\n'
    '    }\n'
    ')\n'
    '_SUBSUMED_CAPABILITIES: Mapping[\n'
    '    Capability,\n'
    '    frozenset[Capability],\n'
    '] = MappingProxyType(\n'
    '    {\n'
    '        Capability.INVESTMENT_DECISION: frozenset(\n'
    '            {\n'
    '                Capability.SECURITY_LOOKUP,\n'
    '                Capability.REALTIME_QUOTE,\n'
    '                Capability.PRICE_HISTORY,\n'
    '                Capability.TECHNICAL_ANALYSIS,\n'
    '                Capability.FUNDAMENTAL_ANALYSIS,\n'
    '                Capability.VALUATION_ANALYSIS,\n'
    '                Capability.FINANCIAL_STATEMENT_ANALYSIS,\n'
    '                Capability.NEWS_ANALYSIS,\n'
    '                Capability.ANNOUNCEMENT_ANALYSIS,\n'
    '                Capability.RISK_ANALYSIS,\n'
    '                Capability.RESEARCH_REPORT_ANALYSIS,\n'
    '                Capability.CATALYST_ANALYSIS,\n'
    '                Capability.STOCK_DEEP_RESEARCH,\n'
    '            }\n'
    '        ),\n'
    '    }\n'
    ')\n'
    '_RUN_ONLY_FRESHNESS = FreshnessPolicy(\n'
    '    reuse_scope=CacheReuseScope.RUN_ONLY,\n'
    ')\n'
    '_FRESHNESS_BY_CAPABILITY: Mapping[\n'
    '    Capability,\n'
    '    FreshnessPolicy,\n'
    '] = MappingProxyType(\n'
    '    {\n'
    '        Capability.REALTIME_QUOTE: _RUN_ONLY_FRESHNESS,\n'
    '        Capability.MARKET_OVERVIEW: _cross_run_freshness(\n'
    '            15,\n'
    '            market_session_sensitive=True,\n'
    '            require_observed_at=True,\n'
    '        ),\n'
    '        Capability.MARKET_MAINLINE_RESEARCH: _cross_run_freshness(\n'
    '            300,\n'
    '            market_session_sensitive=True,\n'
    '            require_observed_at=True,\n'
    '        ),\n'
    '        Capability.CAPITAL_FLOW_ANALYSIS: _cross_run_freshness(\n'
    '            30,\n'
    '            market_session_sensitive=True,\n'
    '            require_observed_at=True,\n'
    '        ),\n'
    '        Capability.PRICE_HISTORY: _cross_run_freshness(\n'
    '            60,\n'
    '            market_session_sensitive=True,\n'
    '            require_observed_at=True,\n'
    '        ),\n'
    '        Capability.TECHNICAL_ANALYSIS: _cross_run_freshness(\n'
    '            60,\n'
    '            market_session_sensitive=True,\n'
    '            require_observed_at=True,\n'
    '        ),\n'
    '        Capability.SECTOR_ANALYSIS: _cross_run_freshness(\n'
    '            60,\n'
    '            market_session_sensitive=True,\n'
    '            require_observed_at=True,\n'
    '        ),\n'
    '        Capability.STOCK_COMPARISON: _cross_run_freshness(\n'
    '            60,\n'
    '            market_session_sensitive=True,\n'
    '            require_observed_at=True,\n'
    '        ),\n'
    '        Capability.STOCK_DEEP_RESEARCH: _cross_run_freshness(\n'
    '            120,\n'
    '            market_session_sensitive=True,\n'
    '            require_observed_at=True,\n'
    '        ),\n'
    '        Capability.INVESTMENT_DECISION: _cross_run_freshness(\n'
    '            120,\n'
    '            market_session_sensitive=True,\n'
    '            require_observed_at=True,\n'
    '        ),\n'
    '        Capability.NEWS_ANALYSIS: _cross_run_freshness(300),\n'
    '        Capability.ANNOUNCEMENT_ANALYSIS: _cross_run_freshness(300),\n'
    '        Capability.RISK_ANALYSIS: _cross_run_freshness(300),\n'
    '        Capability.REGULATORY_ANALYSIS: _cross_run_freshness(300),\n'
    '        Capability.RESEARCH_REPORT_ANALYSIS: _cross_run_freshness(300),\n'
    '        Capability.CATALYST_ANALYSIS: _cross_run_freshness(300),\n'
    '        Capability.SOCIAL_SENTIMENT_ANALYSIS: _cross_run_freshness(300),\n'
    '        Capability.MACRO_ANALYSIS: _cross_run_freshness(300),\n'
    '        Capability.PUBLIC_WEB_RESEARCH: _cross_run_freshness(300),\n'
    '        Capability.FUNDAMENTAL_ANALYSIS: _cross_run_freshness(1_800),\n'
    '        Capability.VALUATION_ANALYSIS: _cross_run_freshness(300),\n'
    '        Capability.FINANCIAL_STATEMENT_ANALYSIS: _cross_run_freshness(1_800),\n'
    '        Capability.THEME_BUSINESS_EVIDENCE: _cross_run_freshness(1_800),\n'
    '        Capability.COLLECTION_FINANCIAL_FILTER: _cross_run_freshness(1_800),\n'
    '        Capability.SECURITY_LOOKUP: _cross_run_freshness(3_600),\n'
    '        Capability.INDUSTRY_RESEARCH: _cross_run_freshness(3_600),\n'
    '        Capability.THEME_STOCK_DISCOVERY: _cross_run_freshness(600),\n'
    '        Capability.STOCK_SCREENING: _cross_run_freshness(300),\n'
    '        Capability.WATCHLIST_QUERY: _RUN_ONLY_FRESHNESS,\n'
    '        Capability.DATA_HEALTH: _RUN_ONLY_FRESHNESS,\n'
    '        Capability.FINANCIAL_SOURCE_DISCOVERY: _cross_run_freshness(3_600),\n'
    '        Capability.FINANCIAL_FEED_READ: _cross_run_freshness(300),\n'
    '        Capability.FINANCIAL_ARTICLE_READ: _cross_run_freshness(3_600),\n'
    '        Capability.WEBPAGE_FEED_TRANSFORM: _RUN_ONLY_FRESHNESS,\n'
    '        Capability.GENERAL_RESPONSE: _RUN_ONLY_FRESHNESS,\n'
    '    }\n'
    ')\n'
    '_READ_CAPABILITIES = {\n'
    '    capability\n'
    '    for capability in Capability\n'
    '    if workflow_for(StandardTaskKind(capability.value)).effect == EffectClass.READ\n'
    '}\n'
    'if set(_FRESHNESS_BY_CAPABILITY) != _READ_CAPABILITIES:\n'
    '    missing = sorted(capability.value for capability in _READ_CAPABILITIES - set(_FRESHNESS_BY_CAPABILITY))\n'
    '    unexpected = sorted(capability.value for capability in set(_FRESHNESS_BY_CAPABILITY) - _READ_CAPABILITIES)\n'
    '    raise RuntimeError(\n'
    '        "freshness registry must cover every read capability exactly; " f"missing={missing}, unexpected={unexpected}"\n'
    '    )\n'
    '@dataclass(frozen=True)\n'
    'class _CapabilitySemantics:\n'
    '    question_types: frozenset[QuestionType]\n'
    '    dimensions: frozenset[EvidenceDimension]\n'
    '    claims: tuple[str, ...]\n'
    '    limitations: tuple[str, ...]\n'
    '    fallbacks: tuple[Capability, ...] = ()\n'
    '    auto_expandable: bool = False\n'
    '_FACT_RESEARCH = frozenset(\n'
    '    {\n'
    '        QuestionType.FACTUAL,\n'
    '        QuestionType.EXPLANATION,\n'
    '        QuestionType.DIAGNOSIS,\n'
    '        QuestionType.COMPARISON,\n'
    '        QuestionType.RESEARCH,\n'
    '    }\n'
    ')\n'
    '_RESEARCH_FORECAST = frozenset(\n'
    '    {\n'
    '        *_FACT_RESEARCH,\n'
    '        QuestionType.FORECAST,\n'
    '    }\n'
    ')\n'
    '_OPERATIONAL = frozenset(\n'
    '    {\n'
    '        QuestionType.FACTUAL,\n'
    '        QuestionType.OPERATION,\n'
    '    }\n'
    ')\n'
)


def initialize(namespace: dict[str, object]) -> None:
    exec(SOURCE, namespace)
