"""Runtime data initialization for the capability registry (part 2)."""

SOURCE = (
    '_SEMANTICS_BY_CAPABILITY: Mapping[\n'
    '    Capability,\n'
    '    _CapabilitySemantics,\n'
    '] = MappingProxyType(\n'
    '    {\n'
    '        Capability.GENERAL_RESPONSE: _sem(\n'
    '            (EvidenceDimension.GENERAL_KNOWLEDGE,),\n'
    '            ("无需实时外部数据的知识、解释、写作或计算",),\n'
    '            ("不能提供本轮未检索的实时市场或公司事实",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.DIRECT,\n'
    '                    QuestionType.FACTUAL,\n'
    '                    QuestionType.EXPLANATION,\n'
    '                }\n'
    '            ),\n'
    '        ),\n'
    '        Capability.SECURITY_LOOKUP: _sem(\n'
    '            (EvidenceDimension.SECURITY_IDENTITY,),\n'
    '            ("证券名称、代码、市场和行业身份",),\n'
    '            ("不能证明公司业务质量、价格或投资价值",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.REALTIME_QUOTE: _sem(\n'
    '            (EvidenceDimension.REALTIME_MARKET,),\n'
    '            ("证券当前行情快照",),\n'
    '            ("不能单独解释涨跌原因或预测后续走势",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.PRICE_HISTORY: _sem(\n'
    '            (EvidenceDimension.PRICE_HISTORY,),\n'
    '            ("证券指定时间范围内的历史行情",),\n'
    '            ("不能单独建立基本面因果或未来主线",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.TECHNICAL_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.TECHNICAL_SIGNALS,),\n'
    '            ("趋势、动量、波动和量价技术状态",),\n'
    '            ("技术信号不是公司基本面或产业主线证据",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.FUNDAMENTAL_ANALYSIS: _sem(\n'
    '            (\n'
    '                EvidenceDimension.COMPANY_BUSINESS,\n'
    '                EvidenceDimension.COMPANY_FINANCIALS,\n'
    '            ),\n'
    '            ("公司业务结构、财务概况和股东结构",),\n'
    '            ("不能替代完整估值、催化或市场交易状态",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.VALUATION_ANALYSIS: _sem(\n'
    '            (\n'
    '                EvidenceDimension.VALUATION,\n'
    '                EvidenceDimension.RESEARCH_CONSENSUS,\n'
    '            ),\n'
    '            ("当前、历史、预期和同行相对估值",),\n'
    '            ("估值便宜不能单独推出可以买入",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.FINANCIAL_STATEMENT_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.FINANCIAL_STATEMENTS,),\n'
    '            ("资产负债表、利润表和现金流量表",),\n'
    '            ("不能单独证明业务竞争力或未来催化",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.NEWS_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.NEWS,),\n'
    '            ("近期公司、行业、市场或宏观新闻及其影响",),\n'
    '            ("媒体报道不能冒充公司正式披露",),\n'
    '            fallbacks=(Capability.PUBLIC_WEB_RESEARCH,),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.ANNOUNCEMENT_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.ANNOUNCEMENTS,),\n'
    '            ("公司正式公告事实",),\n'
    '            ("没有公告不能证明事件不存在",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.RISK_ANALYSIS: _sem(\n'
    '            (\n'
    '                EvidenceDimension.RISK_EVENTS,\n'
    '                EvidenceDimension.ANNOUNCEMENTS,\n'
    '            ),\n'
    '            ("公司已披露或公开可核验的风险事件",),\n'
    '            ("不能把未检索到风险解释为没有风险",),\n'
    '            fallbacks=(Capability.NEWS_ANALYSIS,),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.REGULATORY_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.REGULATORY,),\n'
    '            ("交易所、监管和上市项目动态",),\n'
    '            ("不能替代公司财务或市场行情",),\n'
    '            fallbacks=(Capability.PUBLIC_WEB_RESEARCH,),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.RESEARCH_REPORT_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.RESEARCH_CONSENSUS,),\n'
    '            ("券商研报与一致预期证据",),\n'
    '            ("机构观点属于预测而不是已实现事实",),\n'
    '            fallbacks=(Capability.PUBLIC_WEB_RESEARCH,),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.CATALYST_ANALYSIS: _sem(\n'
    '            (\n'
    '                EvidenceDimension.CATALYSTS,\n'
    '                EvidenceDimension.ANNOUNCEMENTS,\n'
    '                EvidenceDimension.NEWS,\n'
    '            ),\n'
    '            ("未来六至十二个月可回查的公司催化与反向事件",),\n'
    '            ("没有明确时间窗和来源的叙事不能升级为催化",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.SOCIAL_SENTIMENT_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.SOCIAL_SENTIMENT,),\n'
    '            ("公开讨论样本中的情绪分布",),\n'
    '            ("舆情样本不能替代基本面或全市场共识",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.STOCK_COMPARISON: _sem(\n'
    '            (EvidenceDimension.COMPARATIVE_SNAPSHOT,),\n'
    '            ("多只证券在行情、估值、技术与财务上的横向差异",),\n'
    '            ("快照对比不是完整买入判断",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.COMPARISON,\n'
    '                    QuestionType.RESEARCH,\n'
    '                    QuestionType.DECISION,\n'
    '                }\n'
    '            ),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.STOCK_DEEP_RESEARCH: _sem(\n'
    '            (\n'
    '                EvidenceDimension.COMPANY_BUSINESS,\n'
    '                EvidenceDimension.COMPANY_FINANCIALS,\n'
    '                EvidenceDimension.VALUATION,\n'
    '                EvidenceDimension.REALTIME_MARKET,\n'
    '                EvidenceDimension.RISK_EVENTS,\n'
    '                EvidenceDimension.CATALYSTS,\n'
    '            ),\n'
    '            ("完整个股业务、财务、估值、交易状态、风险与催化证据",),\n'
    '            ("深度研究不等于确定性买卖指令",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.RESEARCH,\n'
    '                    QuestionType.DIAGNOSIS,\n'
    '                    QuestionType.COMPARISON,\n'
    '                    QuestionType.FORECAST,\n'
    '                    QuestionType.DECISION,\n'
    '                }\n'
    '            ),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.INVESTMENT_DECISION: _sem(\n'
    '            (\n'
    '                EvidenceDimension.MARKET_MAINLINE,\n'
    '                EvidenceDimension.COMPANY_BUSINESS,\n'
    '                EvidenceDimension.COMPANY_FINANCIALS,\n'
    '                EvidenceDimension.VALUATION,\n'
    '                EvidenceDimension.RISK_EVENTS,\n'
    '                EvidenceDimension.CATALYSTS,\n'
    '            ),\n'
    '            ("八维顺序闸门下的逐股条件买入判断",),\n'
    '            ("只有八维全部通过才允许输出可买入",),\n'
    '            question_types=frozenset({QuestionType.DECISION}),\n'
    '        ),\n'
    '        Capability.MARKET_OVERVIEW: _sem(\n'
    '            (\n'
    '                EvidenceDimension.MARKET_REGIME,\n'
    '                EvidenceDimension.REALTIME_MARKET,\n'
    '            ),\n'
    '            ("指数、市场宽度、成交和整体交易状态",),\n'
    '            ("不能单独识别未来产业主线或建立板块因果",),\n'
    '            fallbacks=(Capability.SECTOR_ANALYSIS,),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.MARKET_MAINLINE_RESEARCH: _sem(\n'
    '            (\n'
    '                EvidenceDimension.MARKET_MAINLINE,\n'
    '                EvidenceDimension.RESEARCH_CONSENSUS,\n'
    '                EvidenceDimension.MACRO_POLICY,\n'
    '                EvidenceDimension.INDUSTRY_STRUCTURE,\n'
    '            ),\n'
    '            ("未来一至六个月当前主线、候选主线及验证条件",),\n'
    '            ("候选主线不是对未来赢家的确定性承诺",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.RESEARCH,\n'
    '                    QuestionType.FORECAST,\n'
    '                    QuestionType.DECISION,\n'
    '                }\n'
    '            ),\n'
    '            fallbacks=(\n'
    '                Capability.MACRO_ANALYSIS,\n'
    '                Capability.INDUSTRY_RESEARCH,\n'
    '                Capability.SECTOR_ANALYSIS,\n'
    '                Capability.PUBLIC_WEB_RESEARCH,\n'
    '            ),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.SECTOR_ANALYSIS: _sem(\n'
    '            (\n'
    '                EvidenceDimension.SECTOR_STRUCTURE,\n'
    '                EvidenceDimension.NEWS,\n'
    '            ),\n'
    '            ("行业或概念板块强弱、资金和近期信息",),\n'
    '            ("单日板块热度不能单独升级为中期市场主线",),\n'
    '            fallbacks=(Capability.NEWS_ANALYSIS,),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.CAPITAL_FLOW_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.CAPITAL_FLOW,),\n'
    '            ("个股多周期资金流持续性",),\n'
    '            ("资金流不能替代公司基本面或主线证据",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.MACRO_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.MACRO_POLICY,),\n'
    '            ("宏观指标、利率和货币政策证据",),\n'
    '            ("宏观证据不能单独推出具体公司结论",),\n'
    '            question_types=_RESEARCH_FORECAST,\n'
    '            fallbacks=(Capability.PUBLIC_WEB_RESEARCH,),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.INDUSTRY_RESEARCH: _sem(\n'
    '            (\n'
    '                EvidenceDimension.INDUSTRY_STRUCTURE,\n'
    '                EvidenceDimension.DOMAIN_CANDIDATES,\n'
    '            ),\n'
    '            ("产业受益链与项目实时板块目录中的候选方向",),\n'
    '            ("产业受益方向不等于公司业务、订单或收入证明",),\n'
    '            question_types=_RESEARCH_FORECAST,\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.THEME_STOCK_DISCOVERY: _sem(\n'
    '            (\n'
    '                EvidenceDimension.DOMAIN_CANDIDATES,\n'
    '                EvidenceDimension.SECURITY_IDENTITY,\n'
    '            ),\n'
    '            ("结构化领域对应的完整板块成分股候选集合",),\n'
    '            ("候选成员关系不等于公司业务匹配",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.FACTUAL,\n'
    '                    QuestionType.RESEARCH,\n'
    '                }\n'
    '            ),\n'
    '        ),\n'
    '        Capability.THEME_BUSINESS_EVIDENCE: _sem(\n'
    '            (\n'
    '                EvidenceDimension.THEME_BUSINESS,\n'
    '                EvidenceDimension.COMPANY_BUSINESS,\n'
    '            ),\n'
    '            ("候选集合逐股主题业务、投入和发展强度",),\n'
    '            ("行业新闻不能代替逐家公司证据",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.RESEARCH,\n'
    '                    QuestionType.COMPARISON,\n'
    '                }\n'
    '            ),\n'
    '        ),\n'
    '        Capability.STOCK_SCREENING: _sem(\n'
    '            (EvidenceDimension.SCREENING,),\n'
    '            ("完整强类型规则下的全市场量化筛选结果",),\n'
    '            ("未声明的筛选条件不会被自动补入",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.FACTUAL,\n'
    '                    QuestionType.RESEARCH,\n'
    '                }\n'
    '            ),\n'
    '        ),\n'
    '        Capability.COLLECTION_FINANCIAL_FILTER: _sem(\n'
    '            (\n'
    '                EvidenceDimension.SCREENING,\n'
    '                EvidenceDimension.COMPANY_FINANCIALS,\n'
    '            ),\n'
    '            ("结构化公司集合上的联合财务条件筛选",),\n'
    '            ("只能消费明确集合，不能扩大股票范围",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.FACTUAL,\n'
    '                    QuestionType.RESEARCH,\n'
    '                }\n'
    '            ),\n'
    '        ),\n'
    '        Capability.WATCHLIST_QUERY: _sem(\n'
    '            (EvidenceDimension.WATCHLIST_STATE,),\n'
    '            ("当前自选和自选分组状态",),\n'
    '            ("自选集合不代表推荐或持仓",),\n'
    '            question_types=_OPERATIONAL,\n'
    '        ),\n'
    '        Capability.WATCHLIST_MUTATION: _sem(\n'
    '            (EvidenceDimension.WATCHLIST_STATE,),\n'
    '            ("按确认动作修改自选成员",),\n'
    '            ("不能在未确认时执行修改",),\n'
    '            question_types=frozenset({QuestionType.OPERATION}),\n'
    '        ),\n'
    '        Capability.WATCHLIST_GROUP_MANAGEMENT: _sem(\n'
    '            (EvidenceDimension.WATCHLIST_STATE,),\n'
    '            ("查看或管理自选分组",),\n'
    '            ("高影响分组修改必须确认",),\n'
    '            question_types=_OPERATIONAL,\n'
    '        ),\n'
    '        Capability.DATA_HEALTH: _sem(\n'
    '            (EvidenceDimension.DATA_QUALITY,),\n'
    '            ("股票池、行情和财务数据覆盖与维护状态",),\n'
    '            ("数据健康不能替代具体投资分析",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.FACTUAL,\n'
    '                    QuestionType.DIAGNOSIS,\n'
    '                }\n'
    '            ),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.FORMAL_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.ANALYSIS_OPERATIONS,),\n'
    '            ("启动或查询正式分析任务",),\n'
    '            ("启动持久任务必须按策略确认",),\n'
    '            question_types=_OPERATIONAL,\n'
    '        ),\n'
    '        Capability.ANALYSIS_HISTORY: _sem(\n'
    '            (EvidenceDimension.ANALYSIS_OPERATIONS,),\n'
    '            ("搜索、读取或删除正式分析历史",),\n'
    '            ("删除操作必须确认",),\n'
    '            question_types=_OPERATIONAL,\n'
    '        ),\n'
    '        Capability.ANALYSIS_TEMPLATE_MANAGEMENT: _sem(\n'
    '            (EvidenceDimension.ANALYSIS_OPERATIONS,),\n'
    '            ("查看或管理分析模板",),\n'
    '            ("模板修改不会自动改变已完成报告",),\n'
    '            question_types=_OPERATIONAL,\n'
    '        ),\n'
    '        Capability.BATCH_ANALYSIS: _sem(\n'
    '            (EvidenceDimension.ANALYSIS_OPERATIONS,),\n'
    '            ("启动指定范围的批量分析",),\n'
    '            ("批量执行必须确认且保持完整范围",),\n'
    '            question_types=frozenset({QuestionType.OPERATION}),\n'
    '        ),\n'
    '        Capability.BATCH_RUN_MANAGEMENT: _sem(\n'
    '            (EvidenceDimension.ANALYSIS_OPERATIONS,),\n'
    '            ("查看或控制批量任务",),\n'
    '            ("控制和删除动作必须确认",),\n'
    '            question_types=_OPERATIONAL,\n'
    '        ),\n'
    '        Capability.ANALYSIS_SCHEDULE_MANAGEMENT: _sem(\n'
    '            (EvidenceDimension.ANALYSIS_OPERATIONS,),\n'
    '            ("查看或修改自动分析计划",),\n'
    '            ("修改计划必须确认",),\n'
    '            question_types=_OPERATIONAL,\n'
    '        ),\n'
    '        Capability.NOTIFICATION: _sem(\n'
    '            (EvidenceDimension.ANALYSIS_OPERATIONS,),\n'
    '            ("检查通知配置或发送确认内容",),\n'
    '            ("发送属于外部副作用，不能自动扩展",),\n'
    '            question_types=_OPERATIONAL,\n'
    '        ),\n'
    '        Capability.FINANCIAL_SOURCE_DISCOVERY: _sem(\n'
    '            (EvidenceDimension.FEED_CONTENT,),\n'
    '            ("助手已筛选 RSSHub 财经来源、参数、健康状态及用途",),\n'
    '            ("来源目录不是资讯内容本身；自动分析按相关性、健康与可信度选择",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.FINANCIAL_FEED_READ: _sem(\n'
    '            (EvidenceDimension.FEED_CONTENT,),\n'
    '            ("指定或上游动态选中 RSSHub Feed 的纯文本结构化内容",),\n'
    '            ("图片、音频和视频不进入结果；路径参数必须由程序校验",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.FINANCIAL_ARTICLE_READ: _sem(\n'
    '            (EvidenceDimension.FEED_CONTENT,),\n'
    '            ("稳定 RSS 条目及其 PDF、Office、表格和纯文本原文件证据",),\n'
    '            ("必须使用 item_ref 或 resource_id 精确绑定；单篇材料不能代表多源共识",),\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.WEBPAGE_FEED_TRANSFORM: _sem(\n'
    '            (EvidenceDimension.FEED_CONTENT,),\n'
    '            ("用户指定网页的 Feed 预览",),\n'
    '            ("转换预览不写入外部系统",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.FACTUAL,\n'
    '                    QuestionType.OPERATION,\n'
    '                }\n'
    '            ),\n'
    '        ),\n'
    '        Capability.FINANCIAL_FEED_EXPORT: _sem(\n'
    '            (EvidenceDimension.FEED_CONTENT,),\n'
    '            ("导出用户指定的纯文本 RSSHub Feed",),\n'
    '            ("导出属于外部副作用，必须确认；媒体字段会被移除",),\n'
    '            question_types=frozenset({QuestionType.OPERATION}),\n'
    '        ),\n'
    '        Capability.PUBLIC_WEB_RESEARCH: _sem(\n'
    '            (EvidenceDimension.PUBLIC_WEB,),\n'
    '            ("内部结构化来源无法覆盖时的公开网页证据",),\n'
    '            ("公开网页不能冒充交易所公告或内部权威数据",),\n'
    '            question_types=_RESEARCH_FORECAST,\n'
    '            auto_expandable=True,\n'
    '        ),\n'
    '        Capability.TRADE_EXECUTION: _sem(\n'
    '            (EvidenceDimension.TRADE_STATE,),\n'
    '            ("独立交易状态机中的账户、风控和订单状态",),\n'
    '            ("当前未接入账户与下单工具，不能执行交易",),\n'
    '            question_types=frozenset(\n'
    '                {\n'
    '                    QuestionType.DECISION,\n'
    '                    QuestionType.OPERATION,\n'
    '                }\n'
    '            ),\n'
    '        ),\n'
    '    }\n'
    ')\n'
    'if set(_SEMANTICS_BY_CAPABILITY) != set(Capability):\n'
    '    missing = sorted(item.value for item in set(Capability) - set(_SEMANTICS_BY_CAPABILITY))\n'
    '    unexpected = sorted(item.value for item in set(_SEMANTICS_BY_CAPABILITY) - set(Capability))\n'
    '    raise RuntimeError(\n'
    '        "semantic registry must cover every capability exactly; " f"missing={missing}, unexpected={unexpected}"\n'
    '    )\n'
)


def initialize(namespace: dict[str, object]) -> None:
    exec(SOURCE, namespace)
